// wordpress/wp-content/themes/astra-child/src/pages/homepage.vue
<template>
  <Header :logo="props.logo" />
  <main class="container mx-auto max-w-[95vmax] lg:max-w-[90vmax] px-4 py-8">
    <SearchForm v-if="props.hero" :current-search="props.hero.currentSearch" :current-lokasi="props.hero.currentLokasi"
      :current-gender="props.hero.currentGender" :current-pendidikan="props.hero.currentPendidikan"
      :current-sort="props.hero.currentSort" :archive-link="props.hero.archiveLink" />
    <JobCarousel v-if="props.carousel" :jobs="props.carousel.jobs" :total-jobs="props.carousel.totalJobs" />
    <JobGrid v-if="props.jobGrid" :jobs="props.jobGrid.jobs" :max-num-pages="props.jobGrid.maxNumPages"
      :context="props.jobGrid.context" :filters="props.jobGrid.filters" :title="props.jobGrid.title"
      :total-jobs="props.jobGrid.totalJobs" />
    <FloatingActionButton />
  </main>
</template>
<script setup lang="ts">
import Header from '@/layouts/Header.vue';
import SearchForm from '@/components/Homepage/SearchForm.vue';
import FloatingActionButton from '@/components/Shared/FloatingActionButton.vue';
import JobGrid from '@/components/Homepage/JobGrid.vue';
import JobCarousel from '@/components/Homepage/JobCarousel.vue';
import type { SearchFormProps, JobGridProps, CarouselProps, LayoutProps } from '@/types'

const props = defineProps<{
  hero: SearchFormProps,
  carousel: CarouselProps,
  jobGrid: JobGridProps,
  logo: LayoutProps['logo']
}>();
</script>

// wordpress/wp-content/themes/wplokerbjm/src/app/routes/Homepage.svelte
<script lang="ts">
  import SearchForm from "@components/ui/Homepage/SearchForm.svelte";
  import JobCarousel from "@components/ui/Homepage/JobCarousel.svelte";
  import JobGrid from "@components/ui/Homepage/JobGrid.svelte";
  import type { CarouselProps, JobGridProps } from "@/types";

  let { carousel, jobGrid } = $props<{
    carousel?: CarouselProps;
    jobGrid?: JobGridProps;
  }>();
</script>

<main class="container mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-8">
  <SearchForm />
  <JobCarousel
    jobs={carousel?.jobs || []}
    title={carousel?.title || "Lowongan Darurat"}
  />
  <JobGrid {...jobGrid} />
</main>
