// wordpress/wp-content/themes/wplokerbjm/src/app/components/ui/Shared/JobCard.svelte
<script lang="ts">
  import { generalStore } from "$lib/stores/General.svelte";
  import { onMount } from "svelte";
  import BookmarkButton from "@components/ui/Shared/BookmarkButton.svelte";
  import { timeEffect } from "$lib/utils/elements.svelte";
  import {
    GlobalNavigateTo,
    routeStateStore,
    routeStore,
  } from "$lib/stores/Route.svelte";
  import { isMobile } from "$lib/utils/elements.svelte";
  import {
    UserTieSolid,
    CalendarSolid,
    ExclamationTriangleSolid,
    ThumbTackSolid,
  } from "svelte-awesome-icons";
  import { SvelteDate } from "svelte/reactivity";
  import type { CardJob, JobCardProps } from "@/types";

  const {
    jobdata = {},
    variant = "carousel",
    permalink = "",
    onClick,
  } = $props<{
    jobdata: CardJob;
    variant: JobCardProps["variant"];
    permalink?: string;
    onClick?: (slug: string, event: MouseEvent, index: number) => void;
    isVisited?: boolean;
  }>();

  const now = $state(new SvelteDate());

  // Derived UI helpers (keeps UI reactive to prop changes)
  const summaryRows = $derived.by(() =>
    generalStore.useSummaryJob(jobdata?.ringkasanPekerjaan),
  );
  const statusInfo = $derived.by(() =>
    generalStore.useStatusJob(Number(jobdata?.status_pekerjaan ?? 0)),
  );
  const deadlineInfo = $derived.by(() =>
    generalStore.useDeadline(jobdata?.deadline, now)(),
  );
  const timeAgo = $derived.by(() =>
    generalStore.useTimeAgo(jobdata?.post_time, now),
  );

  const selected = $derived(routeStateStore.lastVisitedJob === jobdata?.slug);

  const cardClass = $derived.by(() => {
    return `card-base-${variant}${selected ? ` card-selected-${variant}` : ""}`;
  });

  const bodyClass = $derived.by(() => {
    return `card-body-${variant}`;
  });

  function handleClick(event: MouseEvent) {
    const { ctrlKey, metaKey, shiftKey, button } = event as MouseEvent;
    if (ctrlKey || metaKey || shiftKey || button === 1) return;

    // If onClick prop is provided, use it for all navigation (prevents duplicate handling)
    if (onClick) {
      event.preventDefault();
      const slug = jobdata?.slug ?? "";
      onClick(slug, event, 0);
      return;
    }

    if (isMobile()) {
      event.preventDefault();
      if (permalink)
        void GlobalNavigateTo(
          new URL(permalink, routeStore.currentUrl.origin).pathname,
        );
      return;
    }

    // For desktop/tablet: prevent default and handle overlay
    event.preventDefault();
  }

  $effect(() => {
    timeEffect(now);
  });

  onMount(() => {
    if (routeStateStore.restoreVisitedJob()) {
      routeStateStore.restoreVisitedJob();
    }
  });
</script>

<div
  class={`group ${cardClass}`}
  data-job-slug={jobdata?.slug}
  data-job-source={variant === "carousel" ? "carousel" : "grid"}
>
  <a href={permalink} class="contents" onclick={handleClick}>
    <div class={bodyClass}>
      <div class="flex-1 flex flex-col justify-start">
        <div class="flex items-center justify-between mb-2 gap-x-2">
          <h3
            class="card-title font-bold md:text-xl group-hover:text-[var(--wpl-global-color-1)] transition-colors"
          >
            {jobdata?.title}
          </h3>
          <div class="flex items-center gap-2">
            <time
              class="text-lg font-semibold text-center text-[var(--wpl-global-color-1)]"
              datetime={jobdata?.post_time}
            >
              {timeAgo()}
            </time>
          </div>
        </div>

        {#if !jobdata?.nama_perusahaan}
          <div class="divider mt-0"></div>
        {:else}
          <h4 class="font-bold text-lg flex items-center gap-2 mb-6">
            <UserTieSolid
              class="h-6 w-6 text-[var(--wpl-global-color-1)] inline-block"
              aria-hidden="true"
            />
            {jobdata?.nama_perusahaan}
          </h4>
          <div class="divider -mt-4"></div>
        {/if}

        <div
          class="flex flex-wrap gap-x-4 gap-y-1 mb-2 text-[var(--wpl-global-color-1)]"
        >
          {#each summaryRows as row (row.label)}
            {#if row.label !== "Deadline"}
              {@const Icon = row.icon}
              <span
                class="flex items-center text-base md:text-base font-semibold gap-2 py-1"
              >
                {#if Icon}
                  <Icon
                    class="text-[var(--wpl-global-color-1)] w-5 h-5 shrink-0"
                    aria-hidden="true"
                  />
                {/if}
                <span>{row.value ?? ""}</span>
              </span>
            {/if}
          {/each}
        </div>
      </div>

      <div class="divider my-2"></div>

      <div class="flex items-center justify-between font-semibold">
        {#if statusInfo.label}
          <span
            class={[
              "flex items-center badge gap-1 px-3 py-1 font-semibold rounded",
              statusInfo.color,
            ].join(" ")}
          >
            {#if statusInfo.label === "Urgent"}
              <ExclamationTriangleSolid class="h-4 w-4" aria-hidden="true" />
            {:else if statusInfo.label === "Pinned"}
              <ThumbTackSolid class="h-4 w-4" aria-hidden="true" />
            {/if}
            {statusInfo.label}
          </span>
        {/if}
        <div class="flex items-center gap-1 ml-auto">
          {#if deadlineInfo.text}
            <span
              class={[
                "flex items-center badge gap-1 px-3 py-1 font-semibold rounded",
                deadlineInfo.style,
              ].join(" ")}
            >
              <CalendarSolid class="h-4 w-4" aria-hidden="true" />
              <span>{deadlineInfo.text}</span>
            </span>
          {/if}

          {#if variant !== "bookmark"}
            <BookmarkButton jobId={Number(jobdata.id)} {variant} />
          {/if}
        </div>
      </div>
    </div>
  </a>
</div>

<style lang="postcss">
  @reference "@css/app.css";
  div[data-job-slug] {
    /* Make native scrolling consider header height if browser supports this CSS property. */
    scroll-margin-top: var(--site-scroll-padding-top, 0px);
  }
  @utility card-base {
    @apply card block rounded-xl cursor-pointer border-2 border-[var(--wpl-global-color-1)] bg-[var(--wpl-global-color-5)];
  }

  .card-base-carousel {
    @apply card-base max-w-full hover:shadow-lg hover:border-[var(--wpl-global-color-1)];
  }

  .card-selected-carousel {
    @apply ring-2 ring-[var(--wpl-global-color-1)] border-[var(--wpl-global-color-1)] transition-transform translate-y-5;
  }

  .card-base-featured {
    @apply card-base w-full h-full hover:shadow-xl hover:border-[var(--wpl-global-color-1)] hover:scale-[1.02] hover:border-solid;
  }

  .card-selected-featured {
    @apply ring-4 ring-[var(--wpl-global-color-1)] border-[var(--wpl-global-color-1)] transition-transform scale-[1.03];
  }

  .card-body-carousel {
    @apply card-body relative p-3 gap-0 flex flex-col min-h-[300px] h-full;
  }

  .card-body-featured {
    @apply card-body relative p-4 gap-1 flex flex-col h-full;
  }
</style>

// wordpress/wp-content/themes/astra-child/src/components/Homepage/JobCard.vue
<template>
  <article :class="cardClass" @click="handleClick" style="cursor:pointer">
    <a :href="permalink" class="contents">
      <div :class="bodyClass">
        <div class="flex-1 flex flex-col justify-start">
          <div class="flex items-center justify-between mb-2 gap-x-2">
            <h3 class="card-title text-lg md:text-xl !font-bold group-hover:text-blue-700 transition-colors">
              {{ jobdata['title'] }}
            </h3>
            <div class="flex items-center gap-2">
              <time class="text-lg !font-semibold text-center" :datetime="jobdata['post_time']">
                {{ timeAgo }}
              </time>
            </div>
          </div>
          <div v-if="!jobdata['nama_perusahaan']" class="divider mt-0"></div>
          <template v-else>
            <h4 class="!font-bold flex items-center gap-2 !mb-6">
              <i class="fas fa-user-tie !text-[var(--ast-global-color-1)]"></i>
              {{ jobdata['nama_perusahaan'] }}
            </h4>
            <div class="divider !-mt-4"></div>
          </template>
          <div class="flex flex-wrap gap-x-4 gap-y-1 mb-2">
            <template v-for="row in summaryRows" :key="row.label">
              <span v-if="row.label !== 'Deadline'"
                class="flex items-center text-base md:text-base font-semibold gap-2 py-1">
                <i :class="['fas', row.icon, 'text-[var(--ast-global-color-1)]']"></i>
                <span v-html="row.value"></span>
              </span>
            </template>
          </div>
        </div>
        <div class="divider !my-2"></div>
        <div class="flex items-center justify-between !font-semibold">
          <span v-if="statusInfo.label"
            :class="['inline-block !px-3 !py-1 text-sm font-bold rounded', statusInfo.color]">
            {{ statusInfo.label }}
          </span>
          <div class="flex items-center !gap-2 !ml-auto">
            <span v-if="deadlineInfo.text"
              :class="['flex items-center gap-2 !px-3 !py-1 rounded font-semibold !text-sm', deadlineInfo.style]">
              <i class="fas fa-calendar-alt"></i>
              <span>{{ deadlineInfo.text }}</span>
            </span>
            <BookmarkButton :job-id="jobdata.id || 0" :variant="props.variant" />
          </div>
        </div>
      </div>
    </a>
  </article>
</template>

<script lang="ts" setup>
import { computed } from 'vue'
import { useTimeAgo } from '@/composables/useTime'
import { useSummaryJob } from '@/composables/useSummary'
import { useStatusJob } from '@/composables/useStatusJob'
import { useDeadline } from '@/composables/useDeadline'
import { useJobOverlayStore } from '@/stores/JobOverlay'
import BookmarkButton from '@/components/Shared/BookmarkButton.vue'
import type { JobCardProps } from '@/types/Component'

const props = defineProps<JobCardProps>()

const emit = defineEmits(['click'])
const handleClick = (event: MouseEvent) => {
  const isTabletOrDesktop = window.matchMedia('(min-width: 768px)').matches

  const { ctrlKey, metaKey, shiftKey, button } = event
  if (ctrlKey || metaKey || shiftKey || button === 1) return

  event.preventDefault();

  if (!isTabletOrDesktop) {
    window.open(props.permalink, '_blank')
    return
  }

  if (props.variant === 'carousel' && props.onClick) {
    props.onClick(props.jobdata['slug'] ?? '', event, 0)
    const grid = document.getElementById('job-grid')
    if (grid) {
      grid.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
    return
  }

  if (props.variant === 'featured') {
    emit('click', event)
  }
}

const selected = computed(() => props.jobdata['slug'] === useJobOverlayStore().selectedSlug)

const cardClass = computed(() => {
  const baseClasses = {
    carousel: "block group rounded-xl transition-all duration-300 cursor-pointer carousel-card max-w-full border-2 border-blue-400 shadow-md hover:shadow-lg hover:border-blue-600 hover:border-solid",
    featured: "block group rounded-xl transition-all duration-300 cursor-pointer w-full max-w border-2 border-blue-400 shadow-lg hover:shadow-xl hover:border-blue-600 hover:scale-[1.02] hover:border-solid"
  };

  const selectedClasses = {
    carousel: " ring-6 ring-blue-600 border-blue-700",
    featured: " ring-4 ring-blue-500 border-blue-700"
  };

  return `${baseClasses[props.variant] || ""}${selected.value ? selectedClasses[props.variant] || "" : ""}`;
});

const bodyClass = computed(() => {
  const bodyClasses = {
    carousel: "card-body relative p-3 gap-0 flex flex-col min-h-[300px] h-full",
    featured: "card-body relative p-4 gap-1 flex flex-col h-full"
  };

  return bodyClasses[props.variant] || "";
});

const summaryRows = computed(() => useSummaryJob(props.jobdata['ringkasanPekerjaan']))
const statusInfo = computed(() => useStatusJob(Number(props.jobdata['statusjob'])))
const deadlineInfo = computed(() => useDeadline(props.jobdata['deadline']));



const { timeAgo } = useTimeAgo(props.jobdata['post_time'])
</script>
