// wordpress/themes/astra-child/src/components/Homepage/SearchForm/CustomDropdown.vue
<template>
  <div class="relative" tabindex="0" @blur="close" ref="dropdownRef">
    <button type="button"
      class="w-full text-left !px-4 !py-3 border rounded h-12 !bg-[var(--ast-global-color-5)] hover:!ring-2 hover:!ring-color[var(--ast-global-color-1) !text-[var(--ast-global-color-1)]"
      @click="toggle">
      <span class="!pl-6">{{ multiSelectLabel || placeholder }}</span>
      <i class="fas fa-chevron-right float-right !mt-1 transition-transform" :class="{ 'rotate-90': open }"></i>
    </button>
    <ul v-show="open"
      class="absolute left-0 right-0 mt-1 border rounded shadow-lg z-30 max-h-96 overflow-auto py-2 !bg-[var(--ast-global-color-5)]">
      <!-- Search input -->
      <li class="!px-5 !py-2 sticky top-0 z-50 bg-[var(--ast-global-color-5)]">
        <input v-model="search" type="text" class="w-full border rounded px-3 py-2 text-sm focus:outline-none"
          placeholder="Cari..." @keydown.stop />
      </li>
      <!-- Breadcrumb -->
      <li v-if="breadcrumb.length && !search"
        class="!px-5 !py-2 mb-2 flex items-center text-sm !text-[var(--ast-global-color-1)] rounded-t bg-[var(--ast-global-color-5)] sticky top-10 z-40 border-b border-gray-200"
        style="backdrop-filter: blur(2px);">
        <div class="flex items-center gap-2 flex-1 min-w-0 overflow-x-auto">
          <i class="fas fa-sitemap text-blue-600 !mr-2 shrink-0"></i>
          <template v-for="(crumb, idx) in breadcrumb" :key="idx">
            <span v-if="idx < breadcrumb.length - 1"
              class="cursor-pointer hover:underline font-medium flex items-center whitespace-nowrap"
              @mousedown.stop.prevent="goToBreadcrumb(idx)">
              <i class="fas fa-folder-open !mr-1 text-yellow-500"></i>{{ crumb }}
            </span>
            <span v-else class="font-bold flex items-center !text-[var(--ast-global-color-1)] whitespace-nowrap">
              <i class="fas fa-folder !mr-1"></i>{{ crumb }}
            </span>
            <span v-if="idx < breadcrumb.length - 1" class="mx-1 text-gray-400 shrink-0">
              <i class="fas fa-chevron-right"></i>
            </span>
          </template>
        </div>
      </li>
      <!-- Clear filter & Back button -->
      <li
        v-if="(isMultiple && selectedValues.length && !(selectedValues.length === 1 && selectedValues[0]?.value === SEMUA_VALUE)) || (breadcrumb.length && !search)"
        class="flex justify-between items-center !px-5 !py-1">
        <button v-if="breadcrumb.length && !search" type="button"
          class="flex items-center !gap-1 !px-2 !py-0.5 rounded !text-sm bg-blue-50 hover:bg-blue-100 text-blue-600 !font-medium transition"
          @mousedown.stop.prevent="goBack">
          <i class="fas fa-arrow-left text-xs"></i>Kembali
        </button>
        <span></span>
        <button
          v-if="isMultiple && selectedValues.length && !(selectedValues.length === 1 && selectedValues[0]?.value === SEMUA_VALUE)"
          type="button" class="text-blue-600 hover:underline !font-medium !text-sm !px-2 !py-0.5"
          @click="emit('update:modelValue', [SEMUA_VALUE])">
          Hapus filter ini
        </button>
      </li>
      <!-- Options list -->
      <li v-for="(option, idx) in filteredOptions.filter(opt => opt.value !== '')" :key="option.__key" :class="[
        'flex items-center !px-5 !py-2 cursor-pointer select-none transition rounded text-left',
        idx === activeIndex ? '!bg-[var(--ast-global-color-1)]/15' : '',
        isSelected(option.value) ? 'font-bold' : ''
      ]">
        <span class="flex-1 text-left flex items-center" @mouseenter="activeIndex = idx"
          @click="!isMultiple && select(option)">
          <label v-if="isMultiple" class="flex items-center cursor-pointer">
            <input type="checkbox" class="!mr-3 w-6 h-6 accent-blue-500" :checked="isSelected(option.value)"
              @change="toggleValue(option.value)" tabindex="-1" />
          </label>
          <i
            :class="option.children?.length ? 'fas fa-folder !mr-2 text-yellow-400' : 'fas fa-file-alt !mr-2 text-gray-400'"></i>
          <span v-if="search && search.trim()" v-html="highlightMatch(option.label, search)"></span>
          <span v-else>{{ option.label }}</span>
          <span v-if="option.__breadcrumbs && search" class="ml-2 text-xs text-gray-400 italic">({{
            option.__breadcrumbs.join(' / ') }})</span>
          <span v-if="option.isLoading" class="ml-2 text-xs text-gray-400 italic">Memuat...</span>
        </span>
        <button v-if="option.children?.length && !search"
          class="!ml-2 flex items-center justify-center w-10 h-10 rounded hover:!bg-blue-300 relative"
          @mousedown.stop.prevent="navigateChildren(option.children, option.label, option)" tabindex="-1"
          aria-label="Lihat sub">
          <span
            class="absolute -top-2 -right-1 bg-[var(--ast-global-color-1)] text-white text-xs rounded-full px-2 py-0.1 z-10">{{
              option.children.length }}</span>
          <i class="fas fa-chevron-right text-2xl"></i>
        </button>
      </li>
      <li v-if="filteredOptions.length === 0" class="!px-5 !py-2 text-gray-400 text-center">Tidak ada hasil</li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, toRef } from 'vue'
import { useDropdown } from '@/composables/useSearchForm/useDropdown'
import type { Option } from '@/types'
import type { SortOption } from '@/types'

const props = defineProps<{ modelValue: string[] | string | SortOption; options: Option[]; placeholder?: string; multiple?: boolean; disabled?: boolean }>()
const emit = defineEmits(['update:modelValue', 'open'])
const dropdownRef = ref<HTMLElement | null>(null)

const {
  open, activeIndex, search, breadcrumb, selectedValues, multiSelectLabel,
  isSelected, select, toggleValue, isMultiple, SEMUA_VALUE, toggle, close,
  goBack, navigateChildren, goToBreadcrumb, filteredOptions, highlightMatch
} = useDropdown({
  modelValue: toRef(props, 'modelValue') as any,
  options: toRef(props, 'options'),
  emit: emit as (event: string, ...args: any[]) => void,
  multiple: props.multiple,
  placeholder: props.placeholder,
})

function handleClickOutside(e: MouseEvent) {
  if (dropdownRef.value && !dropdownRef.value.contains(e.target as Node)) close()
}
onMounted(() => document.addEventListener('mousedown', handleClickOutside))
onBeforeUnmount(() => document.removeEventListener('mousedown', handleClickOutside))
</script>

// wordpress/wp-content/themes/wplokerbjm/src/app/components/ui/Homepage/CustomDropdown.svelte
<script module lang="ts">
  import type { DropdownOption } from "@/types";
  type ValueProp =
    | string
    | string[]
    | DropdownOption
    | DropdownOption[]
    | undefined;
  type UpdatePayload = string | string[] | undefined;
  type SelectedItem = { value: string; label: string };

  interface Props {
    id?: string;
    value?: ValueProp;
    options?: DropdownOption[];
    placeholder?: string;
    multiple?: boolean;
    disabled?: boolean;
    open?: boolean;
    update?: (payload: UpdatePayload) => void;
    close?: () => void;
  }

  class CustomDropdownHelpers {
    static highlightParts = (label: string, query: string) => {
      const parts: { text: string; match: boolean }[] = [];
      if (!query) return [{ text: label, match: false }];
      const escapeRegex = (s: string) =>
        s.replace(/[.*+?^${}()|[\\]\\]/g, "\\$&");
      const regex = new RegExp(escapeRegex(query), "gi");
      let lastIndex = 0;
      let m: RegExpExecArray | null;
      while ((m = regex.exec(label))) {
        const idx = m.index;
        if (idx > lastIndex) {
          parts.push({ text: label.slice(lastIndex, idx), match: false });
        }
        parts.push({ text: m[0], match: true });
        lastIndex = regex.lastIndex;
      }
      if (lastIndex < label.length) {
        parts.push({ text: label.slice(lastIndex), match: false });
      }
      return parts.length ? parts : [{ text: label, match: false }];
    };

    static flattenOptions(
      optionsList: DropdownOption[],
      breadcrumbs: string[] = []
    ): DropdownOption[] {
      return (optionsList ?? []).flatMap((opt): DropdownOption[] => {
        if (!opt) return [];
        const key = [opt.value, ...breadcrumbs].join(">");
        const baseOption: DropdownOption = {
          ...opt,
          __breadcrumbs: breadcrumbs,
          __key: key,
          children: undefined,
        };
        const nested: DropdownOption[] = opt.children?.length
          ? CustomDropdownHelpers.flattenOptions(opt.children, [
              ...breadcrumbs,
              opt.label,
            ])
          : [];
        return [baseOption, ...nested];
      });
    }

    static normalizeToStringArray(incoming: ValueProp): string[] {
      if (!incoming) return [];
      if (Array.isArray(incoming)) {
        return incoming.map((it) =>
          typeof it === "object" && it !== null && "value" in it
            ? String((it as DropdownOption).value)
            : String(it)
        );
      }
      if (typeof incoming === "object" && "value" in incoming) {
        return [String((incoming as DropdownOption).value)];
      }
      return [String(incoming)];
    }

    static isSelected(v: string, selectedValues: SelectedItem[]): boolean {
      return selectedValues.some((item) => item.value === v);
    }

    static toggleValueLocal(
      v: string,
      value: ValueProp,
      multiple: boolean
    ): string[] {
      const arr = CustomDropdownHelpers.normalizeToStringArray(value);
      const exists = arr.includes(v);
      if (!multiple) return arr;
      return exists ? arr.filter((item) => item !== v) : [...arr, v];
    }
  }

  class CustomDropdownBreadcrumbController {
    static async navigateChildren(
        children: DropdownOption[] | undefined,
        label: string | undefined,
        parentOption: DropdownOption | undefined,
        stack: DropdownOption[][],
        breadcrumbLabels: string[],
      ): Promise<void> {
      if (parentOption?.loadChildren && (!children || !children.length)) {
        parentOption.isLoading = true;
        try {
          parentOption.children = (await parentOption.loadChildren()) ?? [];
        } finally {
          parentOption.isLoading = false;
        }
        stack.push(parentOption.children);
      } else {
        stack.push(children ?? []);
      }
      if (label) breadcrumbLabels.push(label);
    }

    static goBack(
      stack: DropdownOption[][],
      breadcrumbLabels: string[],
    ): void {
      if (stack.length) {
        stack.pop();
        breadcrumbLabels.pop();
      }
    }

    static goToBreadcrumb(
      idx: number,
      stack: DropdownOption[][],
      breadcrumbLabels: string[],
    ): void {
      stack.splice(idx + 1);
      breadcrumbLabels.splice(idx + 1);
    }

    static resetBreadcrumb(
      stack: DropdownOption[][],
      breadcrumbLabels: string[],
    ): void {
      stack.length = 0;
      breadcrumbLabels.length = 0;
    }
  }

  class CustomDropdownController {
    static callUpdate(
      payload: UpdatePayload,
      update?: (payload: UpdatePayload) => void
    ) {
      try {
        if (typeof update === "function") {
          update(payload);
        }
      } catch (err) {
        console.error("CustomDropdown update handler error", err);
      }
    }

    static callClose(close?: () => void) {
      try {
        if (typeof close === "function") {
          close();
          return;
        }
      } catch (err) {
        console.error("CustomDropdown close handler error", err);
      }
    }

    static select(
      option: DropdownOption,
      multiple: boolean,
      value: ValueProp,
      update?: (payload: UpdatePayload) => void,
      close?: () => void,
      resetBreadcrumb?: () => void
    ): void {
      if (multiple) {
        CustomDropdownController.callUpdate(
          CustomDropdownHelpers.toggleValueLocal(option.value, value, multiple),
          update
        );
      } else {
        CustomDropdownController.callUpdate(String(option.value), update);
        CustomDropdownController.callClose(close);
        if (resetBreadcrumb) resetBreadcrumb();
      }
    }

    static clearFilters(update?: (payload: UpdatePayload) => void): void {
      CustomDropdownController.callUpdate([], update);
    }

    static handleClickOutside(
      e: MouseEvent,
      dropdownRef: HTMLElement | null,
      close?: () => void
    ): void {
      if (dropdownRef && !dropdownRef.contains(e.target as Node)) {
        CustomDropdownController.callClose(close);
      }
    }

    static handleFocusOut(
      e: FocusEvent,
      dropdownRef: HTMLElement | null,
      close?: () => void
    ): void {
      const related = e.relatedTarget as Node | null;
      if (!dropdownRef) return;
      if (!related || !dropdownRef.contains(related)) {
        CustomDropdownController.callClose(close);
      }
    }
  }
</script>

<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { taxonomyStore } from "$lib/stores/Taxonomy.svelte";
  import LoadingSpinner from "@components/ui/Shared/LoadingSpinner.svelte";
  import {
    SitemapSolid,
    FolderOpenSolid,
    FolderSolid,
    FileSolid,
    ChevronRightSolid,
    ArrowLeftSolid,
    TrashSolid,
  } from "svelte-awesome-icons";

  let {
    id,
    value = undefined,
    options = [],
    multiple = false,
    open = false,
    update = undefined,
    close = undefined,
  }: Props = $props();

  let search = $state("");
  let breadcrumbLabels = $state<string[]>([]);
  let stack = $state<DropdownOption[][]>([]);
  let activeIndex = $state(0);

  // DOM ref
  let dropdownRef: HTMLElement | null = null;
  let listboxEl = $state<HTMLElement | null>(null);
  const listboxId = String(id ?? "custom-dropdown") + "-listbox";

  const currentOptions = $derived.by(() =>
    stack.length > 0 ? stack[stack.length - 1] : (options ?? [])
  );

  const filteredOptions = $derived.by((): DropdownOption[] => {
    if (String(search).trim()) {
      const q = String(search).trim().toLowerCase();
      return CustomDropdownHelpers.flattenOptions(options ?? []).filter(
        (opt: DropdownOption) => opt.label.toLowerCase().includes(q)
      );
    }
    return (currentOptions ?? []).map((opt: DropdownOption) => ({
      ...opt,
      __key: String(opt.value) + (breadcrumbLabels.join(">") || ""),
    }));
  });

  const filteredNonEmpty = $derived.by((): DropdownOption[] =>
    (filteredOptions ?? []).filter(
      (opt: DropdownOption) => String(opt.value).trim() !== ""
    )
  );

  const selectedValues = $derived.by((): SelectedItem[] => {
    const valArr = CustomDropdownHelpers.normalizeToStringArray(
      value as ValueProp
    ).filter((v) => String(v).trim() !== "");
    const flat = CustomDropdownHelpers.flattenOptions(options ?? []);
    return valArr.map((v) => {
      const found =
        flat.find((o) => o.value === v) ??
        (options ?? []).find((o) => o.value === v);
      return found
        ? { value: String(found.value), label: String(found.label) }
        : { value: v, label: v };
    });
  });

  const onKeyDown = (e: KeyboardEvent): void => {
    if (!open) return;
    const list = (filteredNonEmpty ?? []) as DropdownOption[];

    const keyHandlers = {
      ArrowDown: () => {
        e.preventDefault();
        activeIndex = Math.min((activeIndex ?? 0) + 1, (list.length || 0) - 1);
      },
      ArrowUp: () => {
        e.preventDefault();
        activeIndex =
          (activeIndex ?? 0) > 0
            ? (activeIndex ?? 0) - 1
            : (list.length || 1) - 1;
      },
      ArrowRight: () => {
        e.preventDefault();
        const opt = list[activeIndex as number];
        if (opt && opt.children?.length && !search) {
          CustomDropdownBreadcrumbController.navigateChildren(
            opt.children,
            opt.label,
            opt,
            stack,
            breadcrumbLabels
          );
          activeIndex = 0;
        }
      },
      ArrowLeft: () => {
        e.preventDefault();
        if (breadcrumbLabels.length && !search) {
          CustomDropdownBreadcrumbController.goBack(stack, breadcrumbLabels);
          activeIndex = 0;
        }
      },
      Enter: () => {
        e.preventDefault();
        const opt = list[activeIndex as number];
        if (opt)
          CustomDropdownController.select(
            opt,
            multiple,
            value,
            update,
            close,
            () => {
              CustomDropdownBreadcrumbController.resetBreadcrumb(
                stack,
                breadcrumbLabels
              );
              activeIndex = 0;
              search = "";
            }
          );
      },
      Escape: () => CustomDropdownController.callClose(close),
    };

    keyHandlers[e.key as keyof typeof keyHandlers]?.();
  };

  onMount(() => {
    document.addEventListener("mousedown", (e) =>
      CustomDropdownController.handleClickOutside(e, dropdownRef, close)
    );
    // reference listboxEl to satisfy TS/linter (it's bound in template)
    if (listboxEl) {
      void listboxEl;
    }
  });

  onDestroy(() => {
    document.removeEventListener("mousedown", (e) =>
      CustomDropdownController.handleClickOutside(e, dropdownRef, close)
    );
  });
</script>

<div
  class="relative"
  role="combobox"
  aria-haspopup="listbox"
  aria-controls={listboxId}
  aria-expanded={open}
  tabindex="0"
  onfocusout={(e) =>
    CustomDropdownController.handleFocusOut(e, dropdownRef, close)}
  bind:this={dropdownRef}
  onkeydown={onKeyDown}
>
  {#if open}
    <div
      class="absolute left-0 right-0 mt-2 rounded-lg shadow-lg z-30 pt-2 bg-[var(--wpl-global-color-5)]"
    >
      <!-- Search input (static header above scrollable options) -->
      <div class="px-5 py-2 bg-[var(--wpl-global-color-5)]">
        <input
          bind:value={search}
          type="text"
          class="w-full search-input border rounded px-3 py-2 text-sm ring-1 ring-[var(--wpl-global-color-1)]"
          placeholder="Cari..."
          onkeydown={(e) => e.stopPropagation()}
          oninput={() => (activeIndex = 0)}
        />
      </div>

      <!-- Taxonomy loading shown inside dropdown to avoid parent re-renders -->
      {#if taxonomyStore.loading}
        <div class="px-5 py-2 text-center text-sm text-gray-500">
          <div class="inline-flex items-center justify-center">
            <LoadingSpinner size="sm" srLabel="Memuat..." />
            <span class="ml-2">Memuat data...</span>
          </div>
        </div>
      {/if}

      <!-- Breadcrumb + Clear filter & Back button combined -->
      {#if breadcrumbLabels.length && !search}
        <div
          class="rounded-t bg-[var(--wpl-global-color-5)] text-[var(--wpl-global-color-1)]"
        >
          <!-- breadcrumb header (static under search) -->
          <div
            class="px-5 py-2 pb-2 flex items-center text-sm text-[var(--wpl-global-color-1)] bg-[var(--wpl-global-color-5)] z-40"
          >
            <div class="flex items-center min-w-0 overflow-x-auto pb-2">
              <SitemapSolid class="mr-3 shrink-0" aria-hidden="true" />
              {#each breadcrumbLabels as crumb, idx (crumb + idx)}
                {#if idx < breadcrumbLabels.length - 1}
                  <button
                    type="button"
                    class="cursor-pointer hover:underline font-medium flex items-center whitespace-nowrap"
                    onmousedown={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      CustomDropdownBreadcrumbController.goToBreadcrumb(
                        idx,
                        stack,
                        breadcrumbLabels
                      );
                      activeIndex = 0;
                    }}
                  >
                    <FolderOpenSolid
                      class="mr-1 text-yellow-500"
                      aria-hidden="true"
                    />{crumb}
                  </button>
                  <span class="mx-1 shrink-0"
                    ><ChevronRightSolid aria-hidden="true" /></span
                  >
                {:else}
                  <span
                    class="font-bold flex items-center text-[var(--wpl-global-color-1)] whitespace-nowrap"
                    ><FolderSolid
                      class="mr-1"
                      aria-hidden="true"
                    />{crumb}</span
                  >
                {/if}
              {/each}
            </div>
          </div>

          <!-- controls (static below breadcrumb) -->
          <div
            class="flex justify-between items-center px-5 py-2 z-40 bg-[var(--wpl-global-color-5)] text-[var(--wpl-global-color-1)] bg-opacity-100 border-t"
          >
            <!-- Back button (always available when breadcrumb is present) -->
            <button
              type="button"
              class="dropdown-btn group"
              onmousedown={(e) => {
                e.preventDefault();
                e.stopPropagation();
                CustomDropdownBreadcrumbController.goBack(
                  stack,
                  breadcrumbLabels
                );
                activeIndex = 0;
              }}
              tabindex="-1"
            >
              <ArrowLeftSolid
                class="text-xs no-underline mr-2"
                aria-hidden="true"
              />
              <span class="group-hover:underline">Kembali</span>
            </button>

            {#if multiple && selectedValues.length > 0}
              <button
                type="button"
                class="dropdown-btn hover:underline border rounded-full"
                onclick={() => CustomDropdownController.clearFilters(update)}
              >
                <TrashSolid class="mr-2" aria-hidden="true" />Hapus filter
              </button>
            {/if}
          </div>
        </div>
      {:else if multiple && selectedValues.length > 0}
        <div
          class="flex justify-end items-center px-5 py-1 z-40 bg-[var(--wpl-global-color-5)] text-[var(--wpl-global-color-1)] bg-opacity-100 border-t"
        >
          <button
            type="button"
            class="dropdown-btn hover:underline border rounded-full"
            onclick={() => CustomDropdownController.clearFilters(update)}
          >
            <TrashSolid class="mr-2" aria-hidden="true" />Hapus filter
          </button>
        </div>
      {/if}

      <!-- Options list (scrollable) -->
      <ul
        id={listboxId}
        role="listbox"
        bind:this={listboxEl}
        class="max-h-96 overflow-auto pt-0 pb-2"
      >
        {#each filteredNonEmpty as option, idx (option.__key)}
          <li
            class={[
              "flex items-center px-5 py-2 cursor-pointer select-none transition rounded text-left",
              idx === activeIndex ? "bg-[var(--wpl-global-color-1)]/15" : "",
              CustomDropdownHelpers.isSelected(option.value, selectedValues)
                ? "font-bold"
                : "",
            ].join(" ")}
          >
            <button
              type="button"
              class="flex-1 text-left flex items-center"
              onmouseenter={() => (activeIndex = idx)}
              onclick={() =>
                !multiple &&
                CustomDropdownController.select(
                  option,
                  multiple,
                  value,
                  update,
                  close,
                  () => {
                    CustomDropdownBreadcrumbController.resetBreadcrumb(
                      stack,
                      breadcrumbLabels
                    );
                    activeIndex = 0;
                    search = "";
                  }
                )}
            >
              {#if multiple}
                <label class="flex items-center cursor-pointer"
                  ><input
                    type="checkbox"
                    class="mr-3 w-6 h-6 accent-blue-500"
                    checked={CustomDropdownHelpers.isSelected(
                      option.value,
                      selectedValues
                    )}
                    onchange={() =>
                      CustomDropdownController.callUpdate(
                        CustomDropdownHelpers.toggleValueLocal(
                          option.value,
                          value,
                          multiple
                        ),
                        update
                      )}
                    tabindex="-1"
                  /></label
                >
              {/if}
              {#if option.children?.length}
                <FolderSolid class="mr-2 text-yellow-400" aria-hidden="true" />
              {:else}
                <FileSolid class="mr-2 text-gray-400" aria-hidden="true" />
              {/if}
              {#if search && String(search).trim()}
                {#each CustomDropdownHelpers.highlightParts(option.label, String(search)) as part}
                  {#if part.match}
                    <span
                      class="bg-[var(--wpl-global-color-5)] font-bold rounded px-1"
                      >{part.text}</span
                    >
                  {:else}
                    {part.text}
                  {/if}
                {/each}
              {:else}
                {option.label}
              {/if}
              {#if option.__breadcrumbs && search}
                <span class="ml-2 text-xs text-gray-400 italic"
                  >({option.__breadcrumbs.join(" / ")})</span
                >
              {/if}
              {#if option.isLoading}
                <span
                  class="ml-2 text-xs text-gray-400 italic flex items-center"
                >
                  <LoadingSpinner size="sm" srLabel="Memuat..." />
                  <span class="ml-2">Memuat...</span>
                </span>
              {/if}
            </button>
            {#if option.children?.length && !search}
              <button
                class="ml-2 flex items-center justify-center w-10 h-10 rounded relative transition"
                onclick={(e) => {
                  // stop propagation so the parent row's click/select handler does not run
                  e.stopPropagation();
                  CustomDropdownBreadcrumbController.navigateChildren(
                    option.children,
                    option.label,
                    option,
                    stack,
                    breadcrumbLabels
                  );
                  activeIndex = 0;
                }}
                onmousedown={(e) => {
                  // prevent mousedown from triggering click outside handler
                  e.preventDefault();
                  e.stopPropagation();
                }}
                tabindex="-1"
                aria-label="Lihat sub"
              >
                <span
                  class="absolute -top-2 -right-1 bg-[var(--wpl-global-color-1)] text-xs rounded-full px-2 py-0.1 z-10"
                  >{option.children.length}</span
                >
                <ChevronRightSolid
                  class="border border-[var(--wpl-global-color-1)] hover:bg-[var(--wpl-global-color-1)] rounded-full text-2xl p-1 h-10 w-10"
                  aria-hidden="true"
                />
              </button>
            {/if}
          </li>
        {/each}

        {#if filteredNonEmpty.length === 0 && !taxonomyStore.loading}
          <li class="px-5 py-2 text-gray-400 text-center">Tidak ada hasil</li>
        {/if}
      </ul>
    </div>
  {/if}
</div>

<style lang="postcss">
  @reference "@css/app.css";
  .dropdown-btn {
    @apply flex items-center px-2 p-1 border rounded-full text-sm font-medium;
  }
</style>
