// wordpress/wp-content/themes/astra-child/src/components/Homepage/JobCard.vue
<template>
  <article :class="cardClass" @click="handleClick" style="cursor:pointer">
    <a :href="permalink" class="contents">
      <div :class="bodyClass">
        <div class="flex-1 flex flex-col justify-start">
          <div class="flex items-center justify-between mb-2 gap-x-2">
            <h3 class="card-title text-lg md:text-xl !font-bold group-hover:text-blue-700 transition-colors">
              {{ jobdata['title'] }}
            </h3>
            <div class="flex items-center gap-2">
              <time class="text-lg !font-semibold text-center" :datetime="jobdata['post_time']">
                {{ timeAgo }}
              </time>
            </div>
          </div>
          <div v-if="!jobdata['nama_perusahaan']" class="divider mt-0"></div>
          <template v-else>
            <h4 class="!font-bold flex items-center gap-2 !mb-6">
              <i class="fas fa-user-tie !text-[var(--ast-global-color-1)]"></i>
              {{ jobdata['nama_perusahaan'] }}
            </h4>
            <div class="divider !-mt-4"></div>
          </template>
          <div class="flex flex-wrap gap-x-4 gap-y-1 mb-2">
            <template v-for="row in summaryRows" :key="row.label">
              <span v-if="row.label !== 'Deadline'"
                class="flex items-center text-base md:text-base font-semibold gap-2 py-1">
                <i :class="['fas', row.icon, 'text-[var(--ast-global-color-1)]']"></i>
                <span v-html="row.value"></span>
              </span>
            </template>
          </div>
        </div>
        <div class="divider !my-2"></div>
        <div class="flex items-center justify-between !font-semibold">
          <span v-if="statusInfo.label"
            :class="['inline-block !px-3 !py-1 text-sm font-bold rounded', statusInfo.color]">
            {{ statusInfo.label }}
          </span>
          <div class="flex items-center !gap-2 !ml-auto">
            <span v-if="deadlineInfo.text"
              :class="['flex items-center gap-2 !px-3 !py-1 rounded font-semibold !text-sm', deadlineInfo.style]">
              <i class="fas fa-calendar-alt"></i>
              <span>{{ deadlineInfo.text }}</span>
            </span>
            <BookmarkButton :job-id="jobdata.id || 0" :variant="props.variant" />
          </div>
        </div>
      </div>
    </a>
  </article>
</template>

<script lang="ts" setup>
import { computed } from 'vue'
import { useTimeAgo } from '@/composables/useTime'
import { useSummaryJob } from '@/composables/useSummary'
import { useStatusJob } from '@/composables/useStatusJob'
import { useDeadline } from '@/composables/useDeadline'
import { useJobOverlayStore } from '@/stores/JobOverlay'
import BookmarkButton from '@/components/Shared/BookmarkButton.vue'
import type { JobCardProps } from '@/types/Component'

const props = defineProps<JobCardProps>()

const emit = defineEmits(['click'])
const handleClick = (event: MouseEvent) => {
  const isTabletOrDesktop = window.matchMedia('(min-width: 768px)').matches

  const { ctrlKey, metaKey, shiftKey, button } = event
  if (ctrlKey || metaKey || shiftKey || button === 1) return

  event.preventDefault();

  if (!isTabletOrDesktop) {
    window.open(props.permalink, '_blank')
    return
  }

  if (props.variant === 'carousel' && props.onClick) {
    props.onClick(props.jobdata['slug'] ?? '', event, 0)
    const grid = document.getElementById('job-grid')
    if (grid) {
      grid.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
    return
  }

  if (props.variant === 'featured') {
    emit('click', event)
  }
}

const selected = computed(() => props.jobdata['slug'] === useJobOverlayStore().selectedSlug)

const cardClass = computed(() => {
  const baseClasses = {
    carousel: "block group rounded-xl transition-all duration-300 cursor-pointer carousel-card max-w-full border-2 border-blue-400 shadow-md hover:shadow-lg hover:border-blue-600 hover:border-solid",
    featured: "block group rounded-xl transition-all duration-300 cursor-pointer w-full max-w border-2 border-blue-400 shadow-lg hover:shadow-xl hover:border-blue-600 hover:scale-[1.02] hover:border-solid"
  };

  const selectedClasses = {
    carousel: " ring-6 ring-blue-600 border-blue-700",
    featured: " ring-4 ring-blue-500 border-blue-700"
  };

  return `${baseClasses[props.variant] || ""}${selected.value ? selectedClasses[props.variant] || "" : ""}`;
});

const bodyClass = computed(() => {
  const bodyClasses = {
    carousel: "card-body relative p-3 gap-0 flex flex-col min-h-[300px] h-full",
    featured: "card-body relative p-4 gap-1 flex flex-col h-full"
  };

  return bodyClasses[props.variant] || "";
});

const summaryRows = computed(() => useSummaryJob(props.jobdata['ringkasanPekerjaan']))
const statusInfo = computed(() => useStatusJob(Number(props.jobdata['statusjob'])))
const deadlineInfo = computed(() => useDeadline(props.jobdata['deadline']));



const { timeAgo } = useTimeAgo(props.jobdata['post_time'])
</script>

// wordpress/wp-content/themes/wplokerbjm/src/app/components/ui/Homepage/JobCard.svelte
<script lang="ts">
  import { GeneralStore } from "$lib/stores/General.svelte";
  import BookmarkButton from "@components/ui/Shared/BookmarkButton.svelte";
  import { jobOverlay } from "$lib/stores/JobOverlay.svelte";
  import { navigateTo } from "$lib/stores/route.svelte";
  import type { CardJob, JobCardProps } from "@/types";

  let {
    jobdata = {},
    variant = "carousel",
    permalink = "",
    onClick,
  } = $props<{
    jobdata: CardJob;
    variant: JobCardProps["variant"];
    permalink: string;
    onClick?: (slug: string, event: MouseEvent, index: number) => void;
  }>();

  // Derived UI helpers (keeps UI reactive to prop changes)
  const summaryRows = $derived.by(() =>
    GeneralStore.useSummaryJob(jobdata?.ringkasanPekerjaan)
  );
  const statusInfo = $derived.by(() =>
    GeneralStore.useStatusJob(Number(jobdata?.statusjob ?? 0))
  );
  const deadlineInfo = $derived.by(() =>
    GeneralStore.useDeadline(jobdata?.deadline)
  );
  const timeAgo = GeneralStore.useTimeAgo(jobdata?.post_time);

  const selected = $derived.by(() => {
    try {
      return ($jobOverlay?.selectedSlug ?? null) === (jobdata?.slug ?? null);
    } catch {
      return false;
    }
  });

  const cardClass = $derived.by(() => {
    return `card-base-${variant}${selected ? ` card-selected-${variant}` : ""}`;
  });

  const bodyClass = $derived.by(() => {
    return `card-body-${variant}`;
  });

  async function handleClick(event: MouseEvent) {
    const isTabletOrDesktop =
      typeof window !== "undefined" &&
      window.matchMedia("(min-width: 768px)").matches;
    const { ctrlKey, metaKey, shiftKey, button } = event as MouseEvent;
    if (ctrlKey || metaKey || shiftKey || button === 1) return;

    // If onClick prop is provided, use it for all navigation (prevents duplicate handling)
    if (onClick) {
      event.preventDefault();
      const slug = jobdata?.slug ?? "";
      onClick(slug, event, 0);
      return;
    }

    if (!isTabletOrDesktop) {
      event.preventDefault();
      if (permalink)
        navigateTo(new URL(permalink, window.location.origin).pathname);
      return;
    }

    // For desktop/tablet: prevent default and handle overlay
    event.preventDefault();

    if (variant === "carousel") {
      const slug = jobdata?.slug ?? "";
      // If parent provided an onClick handler (common in grids), delegate and avoid
      // performing a local scroll here — the parent will open overlay and handle a
      // robust scroll that respects sticky/fixed headers.
      if (onClick) {
        event.preventDefault();
        onClick(slug, event, 0);
        return;
      }

      // Otherwise handle opening overlay. Delegate scrolling to the centralized
      // jobOverlay manager so carousel, grid and card all use the same logic.
      await jobOverlay.openOverlay(slug, jobdata);
      // Let the overlay manager handle scrolling after it opens.
      jobOverlay.scrollToCard(slug, 220, 12);
      return;
    }
  }
</script>

<div class={`group ${cardClass}`} data-job-slug={jobdata?.slug}>
  <a href={permalink} class="contents" onclick={handleClick}>
    <div class={bodyClass}>
      <div class="flex-1 flex flex-col justify-start">
        <div class="flex items-center justify-between mb-2 gap-x-2">
          <h3
            class="card-title font-bold md:text-xl group-hover:text-blue-700 transition-colors"
          >
            {jobdata?.title}
          </h3>
          <div class="flex items-center gap-2">
            <time
              class="text-lg font-semibold text-center text-[var(--wpl-global-color-1)]"
              datetime={jobdata?.post_time}
            >
              {timeAgo()}
            </time>
          </div>
        </div>

        {#if !jobdata?.nama_perusahaan}
          <div class="divider mt-0"></div>
        {:else}
          <h4 class="font-bold text-lg flex items-center gap-2 mb-6">
            <svg
              class="h-6 w-6 text-[var(--wpl-global-color-1)] inline-block"
              viewBox="0 0 24 24"
              fill="currentColor"
              aria-hidden="true"
              focusable="false"
            >
              <path
                d="M12 12c2.21 0 4-1.79 4-4S14.21 4 12 4 8 5.79 8 8s1.79 4 4 4zm0 2c-3.31 0-6 2.69-6 6h12c0-3.31-2.69-6-6-6z"
              />
            </svg>
            {jobdata?.nama_perusahaan}
          </h4>
          <div class="divider -mt-4"></div>
        {/if}

        <div class="flex flex-wrap gap-x-4 gap-y-1 mb-2 text-[var(--wpl-global-color-1)]">
          {#each summaryRows as row (row.label)}
            {#if row.label !== "Deadline"}
              {@const Icon = row.icon}
              <span
                class="flex items-center text-base md:text-base font-semibold gap-2 py-1"
              >
                {#if Icon}
                  <Icon
                    class="text-[var(--wpl-global-color-1)] w-5 h-5 shrink-0"
                    aria-hidden="true"
                  />
                {/if}
                <span>{@html row.value ?? ""}</span>
              </span>
            {/if}
          {/each}
        </div>
      </div>

      <div class="divider my-2"></div>

      <div class="flex items-center justify-between font-semibold">
        {#if statusInfo.label}
          <span
            class={[
              "flex items-center badge gap-1 px-3 py-1 font-semibold rounded",
              statusInfo.color,
            ].join(" ")}
          >
            {statusInfo.label}
          </span>
        {/if}
        <div class="flex items-center gap-1 ml-auto">
          {#if deadlineInfo.text}
            <span
              class={[
                "flex items-center badge gap-1 px-3 py-1 font-semibold rounded",
                deadlineInfo.style,
              ].join(" ")}
            >
              <svg
                class="h-4 w-4"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
                focusable="false"
              >
                <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                <line x1="16" y1="2" x2="16" y2="6"></line>
                <line x1="8" y1="2" x2="8" y2="6"></line>
                <line x1="3" y1="10" x2="21" y2="10"></line>
              </svg>
              <span>{deadlineInfo.text}</span>
            </span>
          {/if}

          <!-- Bookmark button migrated to Svelte component -->
          <BookmarkButton jobId={jobdata?.id} {variant} />
        </div>
      </div>
    </div>
  </a>
</div>

<style lang="postcss">
  @reference "@css/app.css";
  div[data-job-slug] {
    /* Make native scrolling consider header height if browser supports this CSS property. */
    scroll-margin-top: var(--site-scroll-padding-top, 0px);
  }
  @utility card-base {
    @apply card block rounded-xl cursor-pointer border-2 border-blue-500;
  }

  .card-base-carousel {
    @apply card block rounded-xl cursor-pointer border-2 border-blue-500 max-w-full hover:shadow-lg hover:border-blue-400;
  }

  .card-selected-carousel {
    @apply ring-2 ring-blue-600 border-blue-700 transition-transform translate-y-5;
  }

  .card-base-featured {
    @apply card block rounded-xl cursor-pointer border-2 border-blue-500 w-full h-full hover:shadow-xl hover:border-blue-600 hover:scale-[1.02] hover:border-solid;
  }

  .card-selected-featured {
    @apply ring-4 ring-blue-500 border-blue-700 transition-transform scale-[1.03];
  }

  .card-body-carousel {
    @apply card-body relative p-3 gap-0 flex flex-col min-h-[300px] h-full;
  }

  .card-body-featured {
    @apply card-body relative p-4 gap-1 flex flex-col h-full;
  }
</style>
