// wordpress/wp-content/themes/astra-child/src/components/Homepage/SearchForm.vue
<template>
  <section class="mx-auto px-4 py-8 text-center">
    <h1 class="text-3xl md:text-5xl !font-bold !mb-2">Temukan Lowongan Kerja Terbaru di Sekitar</h1>
    <p class="mb-8 text-lg !text-semibold">Update setiap hari, mudah diakses, dan gratis!</p>
    <div class="border-2 border-blue-500 rounded-xl p-4 md:p-6 min-h-[220px] sm:min-h-[306px] md:min-h-[204px]">
      <form class="space-y-4" :action="archiveLink" method="get" @submit.prevent="handleSubmit">
        <input type="hidden" name="post_type" value="lowongan" />

        <!-- Search Input with Auto Suggestions -->
        <div class="flex gap-2 relative">
          <input ref="searchInput" type="text" placeholder="Masukkan Pekerjaan atau Perusahaan"
            class="input input-bordered w-full rounded-r-none" name="cari" v-model="searchStore.filters.cari"
            @focus="handleFocus" @blur="searchStore.hideSuggestions" @keydown.enter.prevent="handleSubmit"
            @keydown.down.prevent="navigateSuggestions(1)" @keydown.up.prevent="navigateSuggestions(-1)"
            @keydown.escape="hideSuggestionsImmediate" :disabled="searchStore.loading || taxonomyStore.loading"
            autocomplete="off" />

          <button type="submit" class="btn btn-primary rounded-l-none px-4"
            :class="{ 'opacity-75': searchStore.loading || taxonomyStore.loading }"
            :disabled="searchStore.loading || taxonomyStore.loading">
            <i class="fas"
              :class="(searchStore.loading || taxonomyStore.loading) ? 'fa-spinner fa-spin' : 'fa-search'"></i>
            <span class="sr-only">Cari</span>
          </button>

          <!-- Auto Suggestions Dropdown -->
          <Transition enter-active-class="transition transform ease-out duration-150"
            enter-from-class="opacity-0 scale-90 -translate-y-2" enter-to-class="opacity-100 scale-100 translate-y-0"
            leave-active-class="transition transform ease-in duration-100"
            leave-from-class="opacity-100 scale-100 translate-y-0" leave-to-class="opacity-0 scale-90 -translate-y-2">
            <div v-show="searchStore.showSuggestions && searchStore.hasSuggestions"
              class="auto-suggest-dropdown absolute left-0 sm:left-1/2 sm:-translate-x-1/2 top-full mt-2 min-w-[12rem] w-full sm:w-auto max-w-full sm:max-w-xs md:max-w-md z-20 shadow-lg shadow-blue-200/50">
              <div
                class="bg-blue-100 dark:bg-gray-800 border border-blue-200 dark:border-blue-700 rounded-xl ring-1 ring-blue-100 dark:ring-blue-900">
                <ul class="divide-y divide-blue-200 dark:divide-blue-800 max-h-52 overflow-y-auto">
                  <li v-for="(suggestion, idx) in searchStore.suggestions" :key="`${suggestion}-${idx}`">
                    <a class="block px-4 py-2 text-center text-gray-800 dark:text-white hover:bg-blue-200 dark:hover:bg-blue-900 hover:text-blue-700 dark:hover:text-blue-300 transition-colors cursor-pointer whitespace-nowrap"
                      @click="selectSuggestionUI(suggestion)" @mouseenter="selectedSuggestionIndex = idx">
                      {{ suggestion }}
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </Transition>
        </div>

        <!-- Filter Selects -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <!-- Lokasi -->
          <div class="relative">
            <i
              class="fas fa-map-marker-alt absolute left-3 top-1/2 -translate-y-1/2 text-blue-500 pointer-events-none z-10"></i>
            <button type="button" @mousedown="lokasiLoaded = true" @click="toggleLokasi"
              class="w-full text-left !px-4 !py-3 border rounded h-12 !bg-[var(--ast-global-color-5)] hover:!ring-2 hover:!ring-color[var(--ast-global-color-1) !text-[var(--ast-global-color-1)]">
              <span class="!pl-6">{{ lokasiLabel }}</span>
              <i class="fas fa-chevron-right float-right !mt-1 transition-transform"
                :class="{ 'rotate-90': isLokasiOpen }"></i>
            </button>
            <CustomDropdown id="lokasi" v-if="lokasiLoaded" v-model="searchStore.filters.lokasi"
              :options="mapTerms(taxonomyStore.lokasiTerms, 'Semua lokasi')" placeholder="Semua Lokasi" :multiple="true"
              :disabled="searchStore.loading || taxonomyStore.lokasiLoading" @open="taxonomyStore.fetchLokasiTerms()" />
          </div>
          <!-- Gender -->
          <div class="relative">
            <i
              class="fas fa-venus-mars absolute left-3 top-1/2 -translate-y-1/2 text-blue-500 pointer-events-none z-10"></i>
            <button type="button" @mousedown="genderLoaded = true" @click="toggleGender"
              class="w-full text-left !px-4 !py-3 border rounded h-12 !bg-[var(--ast-global-color-5)] hover:!ring-2 hover:!ring-color[var(--ast-global-color-1) !text-[var(--ast-global-color-1)]">
              <span class="!pl-6">{{ genderLabel }}</span>
              <i class="fas fa-chevron-right float-right !mt-1 transition-transform"
                :class="{ 'rotate-90': isGenderOpen }"></i>
            </button>
            <CustomDropdown id="gender" v-if="genderLoaded" v-model="searchStore.filters.gender"
              :options="mapTerms(taxonomyStore.genderTerms, 'Semua gender')" placeholder="Semua Gender" :multiple="true"
              :disabled="searchStore.loading || taxonomyStore.genderLoading" @open="taxonomyStore.fetchGenderTerms()" />
          </div>
          <!-- Pendidikan -->
          <div class="relative">
            <i
              class="fas fa-graduation-cap absolute left-3 top-1/2 -translate-y-1/2 text-blue-500 pointer-events-none z-10"></i>
            <button type="button" @mousedown="pendidikanLoaded = true" @click="togglePendidikan"
              class="w-full text-left !px-4 !py-3 border rounded h-12 !bg-[var(--ast-global-color-5)] hover:!ring-2 hover:!ring-color[var(--ast-global-color-1) !text-[var(--ast-global-color-1)]">
              <span class="!pl-6">{{ pendidikanLabel }}</span>
              <i class="fas fa-chevron-right float-right !mt-1 transition-transform"
                :class="{ 'rotate-90': isPendidikanOpen }"></i>
            </button>
            <CustomDropdown id="pendidikan" v-if="pendidikanLoaded" v-model="searchStore.filters.pendidikan"
              :options="mapTerms(taxonomyStore.pendidikanTerms, 'Semua pendidikan')" placeholder="Semua Pendidikan"
              :multiple="true" :disabled="searchStore.loading || taxonomyStore.pendidikanLoading"
              @open="taxonomyStore.fetchPendidikanTerms()" />
          </div>
          <!-- Sort -->
          <div class="relative">
            <i
              class="fas fa-sort-amount-down absolute left-3 top-1/2 -translate-y-1/2 text-blue-500 pointer-events-none z-10"></i>
            <button type="button" @mousedown="sortLoaded = true" @click="toggleSort"
              class="w-full text-left !px-4 !py-3 border rounded h-12 !bg-[var(--ast-global-color-5)] hover:!ring-2 hover:!ring-color[var(--ast-global-color-1) !text-[var(--ast-global-color-1)]">
              <span class="!pl-6">{{ sortLabel }}</span>
              <i class="fas fa-chevron-right float-right !mt-1 transition-transform"
                :class="{ 'rotate-90': isSortOpen }"></i>
            </button>
            <CustomDropdown id="sort" v-if="sortLoaded" v-model="searchStore.filters.sort" :options="sortOptions"
              placeholder="Urutkan" :multiple="false" :disabled="searchStore.loading || taxonomyStore.loading" />
          </div>
        </div>

        <!-- Active Filters Display -->
        <div v-if="selectedFiltersWithNames.length" class="!mb-4 flex flex-wrap items-center !gap-2 animate-fade-in">
          <span class="font-semibold text-[var(--ast-global-color-1)] flex items-center justify-center w-full !mr-2">
            <i class="fas fa-filter !mr-1"></i>
            Filter aktif:
          </span>
          <template v-for="filter in selectedFiltersWithNames" :key="filter.key">
            <template v-for="(val, idx) in filter.values" :key="val">
              <span
                class="inline-flex items-center bg-gradient-to-r bg-[var(--ast-global-color-5)] text-sm font-medium !mr-2 !px-3 !py-1 rounded-full shadow-sm transition-all duration-150 hover:shadow-md">
                <i v-if="filter.key === 'lokasi'" class="fas fa-map-marker-alt !mr-1 text-blue-500"></i>
                <i v-else-if="filter.key === 'gender'" class="fas fa-venus-mars !mr-1 text-pink-500"></i>
                <i v-else-if="filter.key === 'pendidikan'" class="fas fa-graduation-cap !mr-1 text-green-500"></i>
                {{ filter.label }}: {{ filter.names[idx] }}
                <button type="button" class="!ml-2 text-blue-500 hover:text-red-600 transition-colors duration-150"
                  @click="removeFilter(searchStore, filter.key as TaxonomyType, val)" aria-label="Hapus filter">
                  <i class="fas fa-times !text-xs"></i>
                </button>
              </span>
            </template>
          </template>
        </div>

        <!-- Reset Filter Button -->
        <div v-if="searchStore.context === 'search'" class="flex justify-end mt-2">
          <button type="button" class="btn btn-outline btn-secondary"
            :disabled="searchStore.loading || taxonomyStore.loading" @click="resetFiltersAndSearch">
            <i class="fas fa-undo mr-2"></i>
            Reset Filter
          </button>
        </div>

        <!-- Error Display -->
        <div
          v-if="searchStore.error || taxonomyStore.lokasiError || taxonomyStore.genderError || taxonomyStore.pendidikanError"
          class="alert alert-error">
          <i class="fas fa-exclamation-triangle"></i>
          <span>
            {{ searchStore.error
              || taxonomyStore.lokasiError
              || taxonomyStore.genderError
              || taxonomyStore.pendidikanError }}
          </span>
        </div>

        <!-- Loading State (search-related only) -->
        <div v-if="searchStore.loading || searchStore.suggestionsLoading"
          class="text-center py-4 flex flex-col items-center justify-center">
          <svg class="animate-spin h-8 w-8 text-blue-500 mb-2" xmlns="http://www.w3.org/2000/svg" fill="none"
            viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"></path>
          </svg>
          <span v-if="searchStore.suggestionsLoading" class="!pl-2">Mencari saran...</span>
          <span v-else class="!pl-2">Mencari...</span>
        </div>

        <!-- Recent Searches (Optional) -->
        <div v-if="searchStore.recentSearches.length" class="mt-4">
          <h4 class="text-sm font-medium text-gray-700 !mb-2">Pencarian Terakhir:</h4>
          <div class="flex flex-wrap !gap-2">
            <button v-for="search in searchStore.recentSearches" :key="search" type="button"
              class="!px-3 !py-1 text-xs bg-gray-100 hover:bg-gray-200 rounded-full"
              @click="searchStore.setFilters({ cari: search })">
              {{ search }}
            </button>
          </div>
        </div>
      </form>
    </div>
  </section>
</template>
<script setup lang="ts">
import type { SearchFormProps, SearchResponse, SortOption } from '@/types'
import { TaxonomyType } from '@/types';
import { useSearchForm } from '@/composables/useSearchForm'
import { useSearchStore } from '@/stores'
import { validation } from '@/utils'
import { defineAsyncComponent, provide, inject } from 'vue';
import { useDropdownController, DROPDOWN_CONTROLLER } from '@/composables/useSearchForm/useDropdown'
const CustomDropdown = defineAsyncComponent(() => import('./SearchForm/CustomDropdown.vue'));

const props = defineProps<SearchFormProps>()

const emit = defineEmits<{
  searchResults: [response: SearchResponse]
  searchError: [error: string]
}>()

const onSearchResults = inject<((searchData: SearchResponse) => void) | null>(
  "onSearchResults",
  null
);

const {
  searchInput,
  searchStore,
  taxonomyStore,
  selectedSuggestionIndex,
  selectSuggestion,
  mapTerms,
  selectedFiltersWithNames
} = useSearchForm(props)

function handleFocus(): void {
  if (searchStore.hasSuggestions) {
    searchStore.showSuggestions = true;
    selectedSuggestionIndex.value = -1;
  }
}

function navigateSuggestions(direction: number): void {
  if (!searchStore.showSuggestions || !searchStore.hasSuggestions) return;

  const maxIndex = searchStore.suggestions.length - 1;

  if (direction > 0) {
    selectedSuggestionIndex.value =
      selectedSuggestionIndex.value < maxIndex
        ? selectedSuggestionIndex.value + 1
        : 0;
  } else {
    selectedSuggestionIndex.value =
      selectedSuggestionIndex.value > 0
        ? selectedSuggestionIndex.value - 1
        : maxIndex;
  }
}

function selectSuggestionUI(suggestion: string): void {
  selectSuggestion(suggestion);
  selectedSuggestionIndex.value = -1;
  handleSubmit();
}

function hideSuggestionsImmediate(): void {
  searchStore.showSuggestions = false;
  selectedSuggestionIndex.value = -1;
}

async function performSearch(): Promise<SearchResponse> {
  if (!validation.isValidFilters(searchStore.filters)) {
    throw new Error("Invalid filters");
  }
  if (selectedSuggestionIndex.value >= 0 && searchStore.hasSuggestions) {
    const suggestion = searchStore.suggestions[selectedSuggestionIndex.value];
    if (suggestion) {
      selectSuggestion(suggestion);
      return await searchStore.searchJobs();
    }
  }
  return await searchStore.searchJobs();
}

async function performReset(): Promise<SearchResponse> {
  searchStore.resetFilters();
  const response = await searchStore.searchJobs();
  searchStore.title = "Lowongan Terbaru";
  searchStore.context = "latest";
  response.title = "Lowongan Terbaru";
  response.context = "latest";
  return response;
}

async function handleSubmit(): Promise<void> {
  try {
    const response = await performSearch();
    hideSuggestionsImmediate();
    emit("searchResults", {
      ...response,
      shouldScroll: true,
      filters: { ...searchStore.filters },
    });
    setTimeout(() => {
      const grid = document.getElementById("job-grid");
      if (grid) grid.scrollIntoView({ behavior: "smooth", block: "start" });
    }, 100);
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "Search failed";
    emit("searchError", errorMessage);
  }
}

async function resetFiltersAndSearch(): Promise<void> {
  try {
    const response = await performReset();
    hideSuggestionsImmediate();
    emit("searchResults", {
      ...response,
      shouldScroll: false,
      filters: { ...searchStore.filters },
    });
    if (onSearchResults)
      onSearchResults({
        ...response,
        shouldScroll: false,
        filters: { ...searchStore.filters },
      });
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "Search failed";
    emit("searchError", errorMessage);
  }
}

function removeFilter(store: ReturnType<typeof useSearchStore>, key: TaxonomyType, value: string): void {
  const arr = Array.isArray(store.filters[key])
    ? [...(store.filters[key] as string[])]
    : [];
  const idx = arr.indexOf(value);
  if (idx !== -1) {
    arr.splice(idx, 1);
    store.filters[key] = arr;
  }
}

const {
  toggleGender,
  togglePendidikan,
  toggleSort,
  toggleLokasi,
  lokasiLabel,
  genderLabel,
  pendidikanLabel,
  sortLabel,
  isLokasiOpen,
  isGenderOpen,
  isPendidikanOpen,
  isSortOpen,
  genderLoaded,
  lokasiLoaded,
  pendidikanLoaded,
  sortLoaded,
  controller
} = useDropdownController()

provide(DROPDOWN_CONTROLLER, controller);

const sortOptions: SortOption[] = [
  { value: 'desc', label: 'Terbaru' },
  { value: 'asc', label: 'Terlama' }
]
</script>

// wordpress/wp-content/themes/wplokerbjm/src/app/components/ui/Homepage/SearchForm.svelte
<script module lang="ts">
  import type { SearchResponse, SortOption } from "@/types";
  import { TaxonomyType } from "@/types";
  import { SearchTitle, SearchContext } from "@/types";
  import { searchStore, SearchUtils } from "$lib/stores/Search.svelte";
  import { dynamicComponentStore } from "$lib/stores/DynamicComponent.svelte";

  type LocalSearchFormProps = {
    currentSearch?: string;
    currentLokasi?: string | string[];
    currentGender?: string | string[];
    currentPendidikan?: string | string[];
    currentSort?: SortOption;
    archiveLink?: string;
    searchResults?: (payload: unknown) => unknown;
    searchError?: (msg: string) => unknown;
  };

  let selectedSuggestionIndex = -1;

  const sortOptions = [
    { value: "desc", label: "Terbaru" },
    { value: "asc", label: "Terlama" },
  ];

  export class SuggestionController {
    static handleFocus() {
      if (searchStore.hasSuggestions) {
        searchStore.showSuggestions = true;
        selectedSuggestionIndex = -1;
      }
    }

    static navigateSuggestions(direction: number) {
      if (!searchStore.showSuggestions || !searchStore.hasSuggestions) return;
      const maxIndex = searchStore.suggestions.length - 1;
      if (direction > 0) {
        selectedSuggestionIndex =
          selectedSuggestionIndex < maxIndex ? selectedSuggestionIndex + 1 : 0;
      } else {
        selectedSuggestionIndex =
          selectedSuggestionIndex > 0 ? selectedSuggestionIndex - 1 : maxIndex;
      }
    }

    static selectSuggestionUI(suggestion: string, onSubmit: () => void) {
      searchStore.selectSuggestion(suggestion);
      selectedSuggestionIndex = -1;
      onSubmit();
    }

    static hideSuggestionsImmediate() {
      searchStore.showSuggestions = false;
      selectedSuggestionIndex = -1;
    }
  }

  export class SearchFormController {
    static async performSearch(): Promise<SearchResponse> {
      if (!searchStore.hasFilters)
        throw new Error("Terjadi kesalahan pada filter");
      searchStore.filters.context = SearchContext.Search;
      if (selectedSuggestionIndex >= 0 && searchStore.hasSuggestions) {
        const suggestion = searchStore.suggestions[selectedSuggestionIndex];
        if (suggestion) {
          searchStore.selectSuggestion(suggestion);
          return await searchStore.searchJobs();
        }
      }
      return await searchStore.searchJobs();
    }

    static async performReset(): Promise<SearchResponse> {
      searchStore.resetFilters();
      const response = await searchStore.searchJobs();
      searchStore.title = SearchTitle.Latest;
      searchStore.context = SearchContext.Latest;
      response.title = SearchTitle.Latest;
      response.context = SearchContext.Latest;
      return response;
    }

    static callSearchResults(
      payload: any,
      searchResults?: (payload: any) => any
    ) {
      try {
        if (typeof searchResults === "function") {
          searchResults(payload);
          return;
        }
      } catch (err) {
        console.error("SearchForm searchResults handler error", err);
      }
    }

    static callSearchError(payload: any, searchError?: (msg: string) => any) {
      try {
        if (typeof searchError === "function") {
          searchError(payload);
          return;
        }
      } catch (err) {
        console.error("SearchForm searchError handler error", err);
      }
    }

    static async handleSubmit(
      e?: Event,
      searchResults?: (payload: any) => any,
      searchError?: (msg: string) => any
    ) {
      e?.preventDefault?.();
      try {
        const response = await SearchFormController.performSearch();
        SuggestionController.hideSuggestionsImmediate();
        SearchFormController.callSearchResults(
          {
            ...response,
            shouldScroll: true,
            filters: { ...searchStore.filters },
          },
          searchResults
        );
        setTimeout(() => {
          const grid = document.getElementById("job-grid");
          if (grid) grid.scrollIntoView({ behavior: "smooth", block: "start" });
        }, 100);
      } catch (err) {
        const errorMessage =
          err instanceof Error ? err.message : "Search failed";
        searchStore.error = errorMessage;
        SearchFormController.callSearchError(errorMessage, searchError);
      }
    }

    static async resetFiltersAndSearch(
      searchResults?: (payload: any) => any,
      searchError?: (msg: string) => any
    ) {
      try {
        const response = await SearchFormController.performReset();
        SuggestionController.hideSuggestionsImmediate();
        SearchFormController.callSearchResults(
          {
            ...response,
            shouldScroll: false,
            filters: { ...searchStore.filters },
          },
          searchResults
        );
      } catch (err) {
        const errorMessage =
          err instanceof Error ? err.message : "Search failed";
        searchStore.error = errorMessage;
        SearchFormController.callSearchError(errorMessage, searchError);
      }
    }
  }

  let CustomDropdown: typeof import("./CustomDropdown.svelte").default | null =
    $state(null);
</script>

<script lang="ts">
  import { onMount } from "svelte";
  import { taxonomyStore } from "$lib/stores/Taxonomy.svelte";
  import LoadingSpinner from "@components/ui/Shared/LoadingSpinner.svelte";
  import {
    MagnifyingGlassSolid,
    MapMarkerAltSolid,
    VenusMarsSolid,
    GraduationCapSolid,
    FilterSolid,
    XmarkSolid,
    RotateLeftSolid,
    TriangleExclamationSolid,
    SortAmountUpSolid,
    SortAmountDownSolid,
  } from "svelte-awesome-icons";

  const props = $props();
  const {
    currentSearch,
    currentLokasi,
    currentGender,
    currentPendidikan,
    currentSort = { value: "desc", label: "Terbaru" },
    archiveLink = "/",
    searchResults = undefined,
    searchError = undefined,
  } = props as LocalSearchFormProps;

  let isLokasiOpen = $state(false);
  let isGenderOpen = $state(false);
  let isPendidikanOpen = $state(false);
  let isSortOpen = $state(false);

  // UI function to remove a filter by key and value
  function removeFilter(key: TaxonomyType | string, value: string) {
    if (key === TaxonomyType.lokasi) {
      const arr = Array.isArray(searchStore.filters[TaxonomyType.lokasi])
        ? [...searchStore.filters[TaxonomyType.lokasi]]
        : [];
      const idx = arr.indexOf(value);
      if (idx !== -1)
        searchStore.filters[TaxonomyType.lokasi] = arr.filter(
          (_, i) => i !== idx
        );
      return;
    }

    if (key === TaxonomyType.gender) {
      const arr = Array.isArray(searchStore.filters[TaxonomyType.gender])
        ? [...searchStore.filters[TaxonomyType.gender]]
        : [];
      const idx = arr.indexOf(value);
      if (idx !== -1)
        searchStore.filters[TaxonomyType.gender] = arr.filter(
          (_, i) => i !== idx
        );
      return;
    }

    if (key === TaxonomyType.pendidikan) {
      const arr = Array.isArray(searchStore.filters[TaxonomyType.pendidikan])
        ? [...searchStore.filters[TaxonomyType.pendidikan]]
        : [];
      const idx = arr.indexOf(value);
      if (idx !== -1)
        searchStore.filters[TaxonomyType.pendidikan] = arr.filter(
          (_, i) => i !== idx
        );
      return;
    }
  }

  // Function to update taxonomy filters
  function updateTaxonomyFilter(taxonomyType: TaxonomyType, payload: unknown) {
    if (!Array.isArray(payload) || payload.length === 0) {
      searchStore.filters[taxonomyType] = [];
      return;
    }
    searchStore.filters[taxonomyType] = SearchUtils.sanitizeArr(payload) ?? [];
  }

  // handle keyboard navigation for the main search input
  function handleInputKeyDown(e: KeyboardEvent) {
    const key = e.key;
    if (key === "Enter") {
      e.preventDefault();
      SearchFormController.handleSubmit(undefined, searchResults, searchError);
      return;
    }
    if (key === "ArrowDown") {
      e.preventDefault();
      SuggestionController.navigateSuggestions(1);
      return;
    }
    if (key === "ArrowUp") {
      e.preventDefault();
      SuggestionController.navigateSuggestions(-1);
      return;
    }
    if (key === "Escape") {
      SuggestionController.hideSuggestionsImmediate();
      return;
    }
  }

  const lokasiLabel = $derived.by(() => {
    const arr = Array.isArray(searchStore.filters[TaxonomyType.lokasi])
      ? searchStore.filters[TaxonomyType.lokasi].filter(
          (s) => typeof s === "string" && String(s).trim() !== ""
        )
      : [];
    if (!arr || arr.length === 0) return "Lokasi Belum Dipilih";
    if (arr.length === 1)
      return taxonomyStore.getTermNameBySlug(TaxonomyType.lokasi, arr[0]);
    return `${arr.length} filter dipilih`;
  });

  const genderLabel = $derived.by(() => {
    const arr = Array.isArray(searchStore.filters[TaxonomyType.gender])
      ? searchStore.filters[TaxonomyType.gender].filter(
          (s) => typeof s === "string" && String(s).trim() !== ""
        )
      : [];
    if (!arr || arr.length === 0) return "Gender Belum Dipilih";
    if (arr.length === 1)
      return taxonomyStore.getTermNameBySlug(TaxonomyType.gender, arr[0]);
    return `${arr.length} filter dipilih`;
  });

  const pendidikanLabel = $derived.by(() => {
    const arr = Array.isArray(searchStore.filters[TaxonomyType.pendidikan])
      ? searchStore.filters[TaxonomyType.pendidikan].filter(
          (s) => typeof s === "string" && String(s).trim() !== ""
        )
      : [];
    if (!arr || arr.length === 0) return "Pendidikan Belum Dipilih";
    if (arr.length === 1)
      return taxonomyStore.getTermNameBySlug(TaxonomyType.pendidikan, arr[0]);
    return `${arr.length} filter dipilih`;
  });

  const sortIsAsc = $derived.by(
    () => (searchStore.filters.sort?.value ?? "") === "asc"
  );

  const updateSortFilter = (payload: unknown) => {
    const defaultSort: SortOption = {
      value: "desc",
      label: "Terbaru",
    };
    if (!payload || Array.isArray(payload)) {
      searchStore.filters.sort = defaultSort;
      return;
    }
    // payload is the underlying value (string)
    const valStr = String(payload);
    if (valStr === "desc" || valStr === "asc") {
      searchStore.filters.sort = {
        value: valStr as "desc" | "asc",
        label: valStr === "desc" ? "Terbaru" : "Terlama",
      };
    } else {
      searchStore.filters.sort = defaultSort;
    }
  };

  $effect(() => {
    if (
      isGenderOpen ||
      isLokasiOpen ||
      isPendidikanOpen ||
      (isSortOpen && !CustomDropdown)
    ) {
      (async () => {
        CustomDropdown = await dynamicComponentStore.loadCustomDropdown();
      })();
    }
  });

  onMount(async () => {
    searchStore.setFilters({
      cari: currentSearch ?? "",
      [TaxonomyType.lokasi]: Array.isArray(currentLokasi)
        ? currentLokasi
        : currentLokasi
          ? [currentLokasi]
          : [],
      [TaxonomyType.gender]: Array.isArray(currentGender)
        ? currentGender
        : currentGender
          ? [currentGender]
          : [],
      [TaxonomyType.pendidikan]: Array.isArray(currentPendidikan)
        ? currentPendidikan
        : currentPendidikan
          ? [currentPendidikan]
          : [],
      sort: currentSort,
    });
  });
</script>

<section class="mx-auto px-4 py-4 text-center">
  <h1 class="text-2xl md:text-3xl mt-4 font-bold mb-2">
    Temukan Lowongan Kerja Terbaru di Sekitar
  </h1>
  <p class="mb-8 text-lg text-semibold">
    Update setiap hari, mudah diakses, dan gratis!
  </p>
  <div
    class="border-2 border-blue-500 mt-4 rounded-xl p-4 md:p-6 min-h-[220px] sm:min-h-[306px] md:min-h-[204px]"
  >
    <form
      class="space-y-4"
      action={archiveLink}
      method="get"
      onsubmit={(e) =>
        SearchFormController.handleSubmit(e, searchResults, searchError)}
    >
      <input type="hidden" name="post_type" value="lowongan" />

      <div class="flex gap-2 relative">
        <input
          type="text"
          placeholder="Masukkan Pekerjaan atau Perusahaan"
          class="input w-full search-input bg-[var(--wpl-global-color-5)]"
          name="cari"
          bind:value={searchStore.filters.cari}
          oninput={() => searchStore.getSuggestions(searchStore.filters.cari)}
          onfocus={SuggestionController.handleFocus}
          onblur={() => searchStore.hideSuggestions()}
          onkeydown={handleInputKeyDown}
          disabled={searchStore.loading || taxonomyStore.loading}
          autocomplete="off"
        />
        <button
          type="submit"
          class="rounded-full border px-4 hover:border"
          class:opacity-75={searchStore.loading || taxonomyStore.loading}
          disabled={searchStore.loading || taxonomyStore.loading}
        >
          {#if searchStore.loading || taxonomyStore.loading}
            <LoadingSpinner size="sm" srLabel="Memuat..." />
          {:else}
            <MagnifyingGlassSolid class="text-base" aria-hidden="true" />
          {/if}
          <span class="sr-only">Cari</span>
        </button>

        {#if searchStore.showSuggestions && searchStore.hasSuggestions}
          <div
            class="absolute left-0 sm:left-1/2 sm:-translate-x-1/2 top-full mt-2 min-w-[12rem] w-full sm:w-auto max-w-full sm:max-w-xs md:max-w-md z-20"
          >
            <div class="bg-[var(--wpl-global-color-5)] rounded-lg">
              <ul class="max-h-52 overflow-y-auto">
                {#each searchStore.suggestions as suggestion, idx}
                  <li>
                    <button
                      type="button"
                      class="w-full text-justify text-sm px-4 py-2 transition-colors cursor-pointer whitespace-nowrap"
                      onclick={() =>
                        SuggestionController.selectSuggestionUI(
                          suggestion,
                          () =>
                            SearchFormController.handleSubmit(
                              undefined,
                              searchResults,
                              searchError
                            )
                        )}
                      onmouseenter={() => (selectedSuggestionIndex = idx)}
                      aria-label={`Pilih saran ${suggestion}`}
                    >
                      {suggestion}
                    </button>
                  </li>
                {/each}
              </ul>
            </div>
          </div>
        {/if}
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="relative">
          <MapMarkerAltSolid
            class="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--wpl-global-color-1)] pointer-events-none z-10"
            aria-hidden="true"
          />
          <button
            type="button"
            class="w-full text-left px-4 py-3 border rounded-full h-12 bg-[var(--wpl-global-color-5)]"
            aria-expanded={isLokasiOpen}
            aria-controls="lokasi-listbox"
            onclick={() => {
              isLokasiOpen = !isLokasiOpen;
              if (isLokasiOpen) {
                isGenderOpen = false;
                isPendidikanOpen = false;
                isSortOpen = false;
                taxonomyStore.fetchLokasiTerms();
              }
            }}><span class="pl-6">{lokasiLabel}</span></button
          >
          {#if isLokasiOpen && CustomDropdown}
            <CustomDropdown
              id="lokasi"
              value={searchStore.filters[TaxonomyType.lokasi]}
              update={(payload) =>
                updateTaxonomyFilter(TaxonomyType.lokasi, payload)}
              options={SearchUtils.mapTerms(
                taxonomyStore.lokasiTerms,
                "Semua lokasi"
              )}
              placeholder="Semua Lokasi"
              multiple={true}
              disabled={searchStore.loading || taxonomyStore.lokasiLoading}
              open={isLokasiOpen}
              close={() => (isLokasiOpen = false)}
            />
          {/if}
        </div>

        <div class="relative">
          <VenusMarsSolid
            class="text-[var(--wpl-global-color-1)] absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none z-10"
            aria-hidden="true"
          />
          <button
            type="button"
            class="w-full text-left px-4 py-3 border rounded-full h-12 bg-[var(--wpl-global-color-5)]"
            aria-expanded={isGenderOpen}
            aria-controls="gender-listbox"
            onclick={() => {
              isGenderOpen = !isGenderOpen;
              if (isGenderOpen) {
                isLokasiOpen = false;
                isPendidikanOpen = false;
                isSortOpen = false;
                taxonomyStore.fetchGenderTerms();
              }
            }}><span class="pl-6">{genderLabel}</span></button
          >
          {#if isGenderOpen && CustomDropdown}
            <CustomDropdown
              id="gender"
              value={searchStore.filters[TaxonomyType.gender]}
              update={(payload) =>
                updateTaxonomyFilter(TaxonomyType.gender, payload)}
              options={SearchUtils.mapTerms(
                taxonomyStore.genderTerms,
                "Semua gender"
              )}
              placeholder="Semua Gender"
              multiple={true}
              disabled={searchStore.loading || taxonomyStore.genderLoading}
              open={isGenderOpen}
              close={() => (isGenderOpen = false)}
            />
          {/if}
        </div>

        <div class="relative">
          <GraduationCapSolid
            class="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--wpl-global-color-1)] pointer-events-none z-10"
            aria-hidden="true"
          />
          <button
            type="button"
            class="w-full text-left px-4 py-3 border rounded-full h-12 bg-[var(--wpl-global-color-5)]"
            aria-expanded={isPendidikanOpen}
            aria-controls="pendidikan-listbox"
            onclick={() => {
              isPendidikanOpen = !isPendidikanOpen;
              if (isPendidikanOpen) {
                isLokasiOpen = false;
                isGenderOpen = false;
                isSortOpen = false;
                taxonomyStore.fetchPendidikanTerms();
              }
            }}><span class="pl-6">{pendidikanLabel}</span></button
          >
          {#if isPendidikanOpen && CustomDropdown}
            <CustomDropdown
              id="pendidikan"
              value={searchStore.filters[TaxonomyType.pendidikan]}
              update={(payload) =>
                updateTaxonomyFilter(TaxonomyType.pendidikan, payload)}
              options={SearchUtils.mapTerms(
                taxonomyStore.pendidikanTerms,
                "Semua pendidikan"
              )}
              placeholder="Semua Pendidikan"
              multiple={true}
              disabled={searchStore.loading || taxonomyStore.pendidikanLoading}
              open={isPendidikanOpen}
              close={() => (isPendidikanOpen = false)}
            />
          {/if}
        </div>

        <div class="relative">
          {#if sortIsAsc}
            <SortAmountUpSolid
              class="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--wpl-global-color-1)] pointer-events-none z-10 w-5 h-5 transform transition-transform duration-150"
              aria-hidden="true"
            />
          {:else}
            <SortAmountDownSolid
              class="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--wpl-global-color-1)] pointer-events-none z-10 w-5 h-5 transform transition-transform duration-150"
              aria-hidden="true"
            />
          {/if}
          <button
            type="button"
            class="w-full text-left px-4 py-3 border rounded-full h-12 bg-[var(--wpl-global-color-5)]"
            aria-expanded={isSortOpen}
            aria-controls="sort-listbox"
            onclick={() => {
              (async () => {
                CustomDropdown = await dynamicComponentStore.loadCustomDropdown();
              })();
              isSortOpen = !isSortOpen;
              if (isSortOpen) {
                isLokasiOpen = false;
                isGenderOpen = false;
                isPendidikanOpen = false;
              }
            }}
            ><span class="pl-6"
              >{searchStore.filters.sort?.label ?? "Urutkan"}</span
            ></button
          >
          {#if isSortOpen && CustomDropdown}
            <CustomDropdown
              id="sort"
              value={searchStore.filters.sort}
              update={(payload) => {
                updateSortFilter(payload);
              }}
              options={sortOptions}
              placeholder="Urutkan"
              multiple={false}
              disabled={searchStore.loading || taxonomyStore.loading}
              open={isSortOpen}
              close={() => (isSortOpen = false)}
            />
          {/if}
        </div>
      </div>

      {#if searchStore.selectedFiltersWithNames && searchStore.selectedFiltersWithNames.length}
        <div class="mb-4 flex flex-wrap items-center gap-2 animate-fade-in">
          <span
            class="font-semibold text-[var(--wpl-global-color-1)] flex items-center justify-center w-full mr-2"
            ><FilterSolid class="mr-1 inline-block" aria-hidden="true" />Filter
            aktif:</span
          >
          {#each searchStore.selectedFiltersWithNames as filter}
            {#each filter.values as val, idx}
              <span
                class="inline-flex items-center bg-gradient-to-r bg-[var(--wpl-global-color-5)] text-sm font-medium mr-2 px-3 py-1 rounded-full shadow-sm transition-all duration-150"
              >
                {#if filter.key === TaxonomyType.lokasi}
                  <MapMarkerAltSolid
                    class="mr-1 text-[var(--wpl-global-color-1)] inline-block"
                    aria-hidden="true"
                  />
                {:else if filter.key === TaxonomyType.gender}
                  <VenusMarsSolid
                    class="mr-1 text-pink-500 inline-block"
                    aria-hidden="true"
                  />
                {:else}
                  <GraduationCapSolid
                    class="mr-1 text-green-500 inline-block"
                    aria-hidden="true"
                  />
                {/if}
                {filter.label}: {filter.names[idx]}
                <button
                  type="button"
                  class="ml-2 text-[var(--wpl-global-color-1)] hover:text-red-600 transition-colors duration-150"
                  onclick={() => removeFilter(filter.key, val)}
                  aria-label="Hapus filter"
                >
                  <XmarkSolid class="text-xs inline-block" aria-hidden="true" />
                </button>
              </span>
            {/each}
          {/each}
        </div>
      {/if}

      {#if searchStore.context === "search"}
        <div class="flex justify-end mt-2">
          <button
            type="button"
            class="p-3 border rounded-full"
            disabled={searchStore.loading || taxonomyStore.loading}
            onclick={() =>
              SearchFormController.resetFiltersAndSearch(
                searchResults,
                searchError
              )}
          >
            <RotateLeftSolid
              class="mr-2 inline-block"
              aria-hidden="true"
            />Reset Filter
          </button>
        </div>
      {/if}

      {#if searchStore.error || taxonomyStore.lokasiError || taxonomyStore.genderError || taxonomyStore.pendidikanError}
        <div class="alert alert-error">
          <TriangleExclamationSolid
            class="mr-2 inline-block text-red-600"
            aria-hidden="true"
          />
          <span
            >{searchStore.error ||
              taxonomyStore.lokasiError ||
              taxonomyStore.genderError ||
              taxonomyStore.pendidikanError}</span
          >
        </div>
      {/if}

      {#if searchStore.loading || searchStore.suggestionsLoading}
        <div class="text-center py-4 flex flex-col items-center justify-center">
          <LoadingSpinner srLabel="Memuat..." size="md" />
          <span class="mt-2"
            >{searchStore.suggestionsLoading
              ? "Mencari saran..."
              : "Mencari..."}</span
          >
        </div>
      {/if}

      {#if searchStore.recentSearches && searchStore.recentSearches.length}
        <div class="mt-4">
          <span class="text-lg font-semibold"> Pencarian Terakhir: </span>
          <div class="flex flex-wrap font-semibold gap-2 mt-4">
            {#each searchStore.recentSearches as item}
              <button
                type="button"
                class="px-3 py-1 text-xs bg-[var(--wpl-global-color-5)] hover:bg-[var(--wpl-global-color-7)] rounded-full"
                onclick={() => searchStore.setFilters({ cari: item })}
                >{item}</button
              >
            {/each}
          </div>
        </div>
      {/if}
    </form>
  </div>
</section>

<style lang="postcss">
  @reference "@css/app.css";
  button {
    @apply text-[var(--wpl-global-color-1)] hover:border-3;
  }
</style>
