// wordpress/wp-content/themes/astra-child/src/components/Homepage/JobGrid/SingleOverlay.vue
<template>
  <div v-if="visible" class="min-h-screen flex flex-col pointer-events-auto ml-7">
    <!-- Overlay background (only in JobGrid area) -->
    <div class="absolute top-0 left-0 right-0 bottom-0" @click="close"></div>
    <!-- Drawer -->
    <aside v-if="visible"
      class="relative bg-[var(--ast-global-color-4)] shadow-xl transition-transform duration-300 rounded-xl border-2 border-blue-400 w-full max-h-screen overflow-y-auto flex flex-col z-50"
      :class="drawerOpenClass">
      <button class="absolute top-5 right-4" @click="close" aria-label="Close">
        Tutup
      </button>
      <a v-if="!loading && overlay && props.permalink" :href="props.permalink" target="_blank" rel="noopener"
        class="absolute top-5 left-4 btn btn-sm btn-outline btn-primary flex items-center gap-1">
        <i class="fas fa-external-link-alt"></i>
        Buka di Tab Baru
      </a>
      <a v-if="!loading && overlay && isLoggedIn && editPostId"
        :href="`/wp-admin/post.php?post=${editPostId}&action=edit`" target="_blank" rel="noopener"
        class="absolute top-5 left-44 btn btn-sm btn-outline btn-warning flex items-center gap-1">
        <i class="fas fa-edit"></i>
        Edit
      </a>
      <a v-if="!loading && overlay && isLoggedIn && editPostId" :href="getCloneHref(editPostId)" target="_blank"
        rel="noopener" class="absolute top-5 left-96 btn btn-sm btn-outline btn-success flex items-center gap-1">
        <i class="fas fa-copy"></i>
        Clone Draft
      </a>
      <div v-if="loading" class="p-4 text-center pt-16 flex-1 flex flex-col items-center justify-center">
        <span class="sr-only">Memuat...</span>
        <svg class="animate-spin h-8 w-8 text-blue-500 mb-4" xmlns="http://www.w3.org/2000/svg" fill="none"
          viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"></path>
        </svg>
        Memuat Lowongan...
      </div>
      <div v-else-if="error" class="p-4 text-red-500 pt-16 flex-1">{{ error }}</div>
      <div v-else-if="overlay" class="p-6 space-y-8 pt-16 flex-1 flex flex-col">
        <JobDetail :job="overlay" />
      </div>
    </aside>
  </div>
</template>

<script setup lang="ts">
import { defineAsyncComponent, onMounted, onUnmounted } from 'vue';
import { useSingleOverlay } from '@/composables/useJobGrid/useSingleOverlay'
const JobDetail = defineAsyncComponent(() => import('@/components/Shared/JobDetail.vue'));
const props = defineProps<{
  slug: string
  visible: boolean
  permalink?: string
}>();
const emit = defineEmits(['close'])

const {
  data,
  loading,
  error,
  isLoggedIn,
  editPostId,
  getCloneHref,
} = useSingleOverlay(props)

const overlay = data

function close() {
  emit('close')
}

function onkeydown(event: KeyboardEvent) {
  if (event.key === 'Escape') {
    close()
  }
}
onMounted(() => {
  document.addEventListener('keydown', onkeydown)
})
onUnmounted(() => {
  document.removeEventListener('keydown', onkeydown)
})
const drawerOpenClass = 'transform translate-x-0'
</script>

// wordpress/wp-content/themes/wplokerbjm/src/lib/components/ui/Homepage/SingleOverlay.svelte
<script module lang="ts">
  import { nonceManager } from "$lib/utils/Nonce.svelte";
  import LoadingSpinner from "@components/ui/Shared/LoadingSpinner.svelte";
  import { PenToSquareSolid, CopySolid } from "svelte-awesome-icons";
  import { jobOverlay } from "$lib/stores/JobOverlay.svelte";
  import JobDetail from "@components/ui/Shared/JobDetail.svelte";
  import SkeletonSingleLowongan from "@components/ui/Skeletons/SkeletonSingleLowongan.svelte";
  import { getCmsOrigin } from "@/utils";

  let slideIn = $state(false);

  const data = $derived(jobOverlay.overlayData);
  const editPostId = $derived(data?.id ?? null);

  function isLoggedIn(): boolean {
    if (nonceManager.getNonce) {
      return true;
    }
    return false;
  }

  function getCloneHref(postId?: number | null): string {
    if (!postId) return "#";
    const base = `${getCmsOrigin()}/wp-admin/admin.php?action=dt_dpp_post_as_draft&post=${postId}`;

    try {
      const dup = data?.duplicateNonce;
      if (typeof dup === "string" && dup.length > 0)
        return `${base}&nonce=${encodeURIComponent(dup)}`;
    } catch {
      // Ignore errors and return base URL
    }

    return base;
  }
</script>

<script lang="ts">
  import { onMount, tick } from "svelte";
  import { page } from "$app/state";
  import type { JobDetailResponse } from "@/types";
  import { routeStore } from "@/lib/stores/Route.svelte";

  const { visible } = $props<{
    visible: boolean;
  }>();

  const pageJob = $derived((page.data?.job as JobDetailResponse | null) ?? null);
  
  $effect(() => {
  jobOverlay.overlayData = pageJob;
    if (visible) {
      slideIn = false;
      tick().then(() => {
        slideIn = true;
      });
    } else {
      slideIn = false;
    }
  });

  onMount(() => {
    const timeoutId = setTimeout(() => {
      isLoggedIn();
    }, 2000);

    return () => {
      clearTimeout(timeoutId);
    };
  });
</script>

<!--
  Keep the overlay DOM mounted at all times so that its internal scroll
  position isn't lost when reopening.  The previous implementation used
  `{#if visible}` which destroyed the element every time and caused
  the user to lose their place inside the drawer.
-->
<div
  data-last-error=""
  aria-hidden={!visible}
  class={[
    "min-h-screen flex flex-col ml-7 transition-transform duration-600 ease-in-out",
    slideIn ? "transform translate-x-0" : "transform translate-x-full",
    visible ? "pointer-events-auto" : "pointer-events-none",
    !visible ? "opacity-0" : "opacity-100",
  ]
    .filter(Boolean)
    .join(" ")}
>
  <!-- Overlay background (only in JobGrid area) -->
  <div class="absolute top-0 left-0 right-0 bottom-0"></div>

  <!-- Drawer -->
  <aside
    class="relative shadow-xl rounded-xl border-2 border-[var(--wpl-global-color-1)] bg-[var(--wpl-global-color-5)] w-full max-h-[calc(100vh-var(--site-scroll-padding-top)-var(--site-header-height))] overflow-y-auto flex flex-col z-50"
  >
    <div
      class="flex absolute top-5 left-4 right-4 justify-between items-center z-10 gap-4"
      role="toolbar"
      aria-label="Overlay controls"
    >
      <div class="flex items-center gap-2">
        {#if !routeStore.isLoading && data && isLoggedIn() && editPostId}
          <a
            href={`${getCmsOrigin()}/wp-admin/post.php?post=${editPostId}&action=edit`}
            target="_blank"
            rel="noopener noreferrer"
            class="btn btn-sm btn-outline btn-warning flex items-center gap-1"
          >
            <PenToSquareSolid class="mr-1" aria-hidden="true" />
            <span>Edit</span>
          </a>
        {/if}
      </div>

      <div class="flex items-center gap-2">
        {#if !routeStore.isLoading && data && isLoggedIn() && editPostId}
          <a
            href={getCloneHref(editPostId)}
            target="_blank"
            rel="noopener noreferrer"
            class="btn btn-sm btn-outline btn-success flex items-center gap-1"
          >
            <CopySolid class="mr-1" aria-hidden="true" />
            <span>Clone Draft</span>
          </a>
        {/if}
      </div>
    </div>

    {#if routeStore.isLoading}
      <div
        class="p-4 text-center pt-16 flex-1 flex flex-col items-center justify-center"
      >
        <span class="mt-4 mb-4 text-2xl font-bold">Memuat Lowongan...</span>
        <LoadingSpinner srLabel="Memuat..." size="md" />
        <SkeletonSingleLowongan />
      </div>
    {:else if !data}
      <!-- Placeholder skeleton when no job selected -->
      <div class="p-6 space-y-8 pt-16 flex-1 flex flex-col">
        <span class="text-lg font-bold mb-4 text-center"
          >Silahkan pilih lowongan untuk melihat detailnya.</span
        >
        <SkeletonSingleLowongan />
      </div>
    {:else if data}
      <div class="p-6 space-y-8 pt-16 flex-1 flex flex-col">
        <JobDetail job={data} />
      </div>
    {/if}
  </aside>
</div>
