// wordpress/wp-content/themes/wplokerbjm/src/lib/components/ui/Shared/BookmarkButton.svelte
<script lang="ts">
  import { bookmarkStore } from "$lib/stores/Bookmark.svelte";
  import type { JobCardProps, WPBasePost } from "@/types";
  import { BookmarkSolid, TrashAltSolid } from "svelte-awesome-icons";
  import { dynamicComponentStore } from "$lib/stores/DynamicComponent.svelte";
  import { useRIC } from "$lib/utils/window.svelte";

  interface Props {
    jobId: WPBasePost["id"];
    variant: JobCardProps["variant"];
  }
  const { jobId, variant = undefined }: Props = $props();

  const isJobSaved = $derived(
    bookmarkStore.jobs.some((job) => Number(job.id) === jobId),
  );
  const toggleSave = (id: number) => bookmarkStore.toggleSave(id);

  let isLoading = $state(false);
  let isHovered = $state(false);
  let confirmationState: "saved" | "removed" | null = $state(null);
  let errorState: "save" | "remove" | null = $state(null);
  let isPending = $state(false);
  let isTouchDevice = $derived.by(() => {
    if (typeof window === "undefined") return false;
    return "ontouchstart" in window || navigator.maxTouchPoints > 0;
  });

  let preToggleSaved = $state(false);
  // synchronous lock to prevent same-tick re-entrancy from multiple rapid DOM clicks
  let clicklock = false;

  function handleToggleSave(e: MouseEvent) {
    // prevent parent handlers
    e.preventDefault();
    e.stopPropagation();
    if (isNaN(jobId) || jobId < 1) return;

    // If this tab is outdated (a newer build is open elsewhere), do a cache-reload fetch then force navigation.
    if (typeof window !== "undefined" && bookmarkStore.isOutdated) {
      fetch(window.location.href, { cache: "reload" }).then(() => {
        window.location.reload();
      });
      return;
    }

    const preloadBookmarkModal = () => {
      if (!dynamicComponentStore.BookmarkModal) {
        void dynamicComponentStore.loadBookmarkModal();
      }
    };

    useRIC(preloadBookmarkModal, { fallbackDelay: 200 });

    // protect against both reactive loading state and synchronous re-entry
    if (isLoading || clicklock) return;

    clicklock = true;

    isLoading = true;
    preToggleSaved = isJobSaved;
    isPending = true;
    try {
      const wasSaved = isJobSaved;
      toggleSave(jobId).then(() => {
        isPending = false;
        if (!wasSaved) {
          confirmationState = "saved";
        } else {
          confirmationState = "removed";
        }
      });
    } catch {
      isPending = false;
      const wasSaved = preToggleSaved;
      errorState = wasSaved ? "remove" : "save";
    } finally {
      isLoading = false;
      clicklock = false;
      const duration =
        confirmationState !== null ? 1000 : errorState !== null ? 3000 : 1000; // shorter duration if only showing error
      setTimeout(() => {
        confirmationState = null;
        errorState = null;
      }, duration);
    }
  }

  const buttonSizeClass = $derived.by(() => {
    switch (variant) {
      case "carousel":
        return "btn-sm btn-circle ";
      case "featured":
        return "btn-md btn-circle ";
      default:
        return "btn-md btn-circle ";
    }
  });

  function useBookmarkStyle(
    saved: boolean,
    showConfirmation: boolean,
  ): { style: string } {
    if (!saved) return { style: "text-gray-600" };
    if (showConfirmation) return { style: "text-green-700" };
    return { style: "text-red-700" };
  }

  const bookmarkStyle = $derived(
    useBookmarkStyle(isJobSaved, confirmationState === "saved"),
  );

  // New reactive icon spec: name and optional classes (color override)
  const displayedIconSpec = $derived.by(() => {
    if (isPending) {
      return preToggleSaved
        ? { name: "trash", classes: "text-red-400" }
        : { name: "bookmark", classes: "text-[var(--wpl-global-color-1)] " };
    }
    const saved = isJobSaved;
    return saved
      ? { name: "trash", classes: "text-red-400" }
      : { name: "bookmark", classes: "text-[var(--wpl-global-color-1)] " };
  });

  const borderIconSpec = $derived.by(() => {
    if (isPending) {
      return preToggleSaved
        ? "border-red-400 "
        : "border-[var(--wpl-global-color-1)] ";
    }

    const saved = isJobSaved;
    if (saved) {
      return "border-red-400 ";
    } else {
      return "border-[var(--wpl-global-color-1)] ";
    }
  });

  const iconSizeClass = $derived.by(() => {
    switch (variant) {
      case "carousel":
        return "h-4 w-4 ";
      case "featured":
        return "h-5 w-5 ";
      default:
        return "h-5 w-5 ";
    }
  });
</script>

<div class="relative flex items-center">
  <button
    type="button"
    onclick={handleToggleSave}
    onmouseenter={() => (isHovered = true)}
    onmouseleave={() => (isHovered = false)}
    class={"rounded-full flex items-center justify-center border-1 hover:border-2 transition-colors duration-300 " +
      buttonSizeClass +
      borderIconSpec +
      (isLoading ? " !opacity-50 cursor-not-allowed " : "") +
      bookmarkStyle.style}
    disabled={isLoading}
    title={isJobSaved ? "Hapus bookmark" : "Simpan lowongan"}
    aria-label="Bookmark job"
    aria-pressed={isJobSaved}
  >
    {#if displayedIconSpec.name === "bookmark"}
      <BookmarkSolid
        class={`${iconSizeClass} ${displayedIconSpec.classes}`}
        aria-hidden="true"
      />
    {:else}
      <TrashAltSolid
        class={`${iconSizeClass} ${displayedIconSpec.classes}`}
        aria-hidden="true"
      />
    {/if}
  </button>

  {#if !isTouchDevice && isHovered && !isLoading}
    {@const hapus = isJobSaved}
    <div class="absolute -top-8 right-0 flex items-center pointer-events-none">
      <div
        class={`${hapus ? "bg-red-400 " : "bg-[var(--wpl-global-color-1)] "} text-white text-xs font-semibold px-2 py-1 rounded shadow-sm`}
      >
        {hapus ? "Hapus?" : "Simpan?"}
      </div>
    </div>
  {/if}

  {#if confirmationState !== null}
    <div
      class="absolute -top-8 right-0 flex items-center"
      role="status"
      aria-live="polite"
    >
      {#if confirmationState === "saved"}
        <div
          class="bg-green-600 text-white text-xs font-semibold px-2 py-1 rounded shadow-sm"
        >
          Tersimpan
        </div>
      {:else}
        <div
          class="bg-gray-700 text-white text-xs font-semibold px-2 py-1 rounded shadow-sm"
        >
          Terhapus
        </div>
      {/if}
    </div>
  {/if}

  {#if errorState !== null}
    <div
      class="absolute -top-8 right-0 flex items-center"
      role="alert"
      aria-live="assertive"
    >
      <div
        class="bg-red-600 text-white text-xs font-semibold px-2 py-1 rounded shadow-sm"
      >
        {errorState === "save" ? "Gagal menyimpan" : "Gagal menghapus"}
      </div>
    </div>
  {/if}
</div>

// wordpress/wp-content/themes/astra-child/src/components/Shared/BookmarkButton.vue
<template>
    <div class="relative flex items-center">
        <span @click.prevent.stop="handleToggleSave" @mouseenter="isHovered = true" @mouseleave="isHovered = false"
            :disabled="isLoading" :class="[
                'rounded-full transition-colors',
                buttonSizeClass,
                bookmarkStyle.style,
                { '!opacity-50 cursor-not-allowed': isLoading }
            ]" :title="isSaved(props.jobId) ? 'Hapus bookmark' : 'Simpan lowongan'" aria-label="Bookmark job"
            :aria-pressed="isSaved(props.jobId)" role="button">
            <i :class="displayedIconClass"></i>
        </span>

        <!-- hover bubble asking for confirmation: 'Simpan?' or 'Hapus?' -->
        <div v-if="isHovered && !isLoading" class="absolute -top-8 right-0 flex items-center pointer-events-none">
            <div class="bg-[var(--ast-global-color-1)] text-white text-xs font-semibold px-2 py-1 rounded shadow-sm">
                {{ isSaved(props.jobId) ? 'Hapus?' : 'Simpan?' }}
            </div>
        </div>

        <!-- confirmation bubble with fade/slide animation -->
        <transition enter-active-class="transition ease-out duration-200" enter-from-class="opacity-0 translate-y-2"
            enter-to-class="opacity-100 translate-y-0" leave-active-class="transition ease-in duration-150"
            leave-from-class="opacity-100 translate-y-0" leave-to-class="opacity-0 translate-y-2">
            <div v-if="confirmationState !== null" class="absolute -top-8 right-0 flex items-center" role="status"
                aria-live="polite">
                <div v-if="confirmationState === 'saved'"
                    class="!bg-green-600 text-white text-xs font-semibold !px-2 !py-1 rounded !shadow-sm">
                    Tersimpan
                </div>
                <div v-else-if="confirmationState === 'removed'"
                    class="!bg-gray-700 text-white text-xs font-semibold !px-2 !py-1 rounded !shadow-sm">
                    Terhapus
                </div>
            </div>
        </transition>

        <!-- error bubble -->
        <transition enter-active-class="transition ease-out duration-200" enter-from-class="opacity-0 translate-y-2"
            enter-to-class="opacity-100 translate-y-0" leave-active-class="transition ease-in duration-150"
            leave-from-class="opacity-100 translate-y-0" leave-to-class="opacity-0 translate-y-2">
            <div v-if="errorState !== null" class="absolute -top-8 right-0 flex items-center" role="alert"
                aria-live="assertive">
                <div class="!bg-red-600 text-white text-xs font-semibold !px-2 !py-1 rounded !shadow-sm">
                    {{ errorState === 'save' ? 'Gagal menyimpan' : 'Gagal menghapus' }}
                </div>
            </div>
        </transition>
    </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useBookmark } from '@/composables/useBookmark'

const props = defineProps<{
    jobId: number
    variant?: 'carousel' | 'featured' | 'detail'
}>()

const { isSaved, toggleSave } = useBookmark()

const confirmationState = ref<'saved' | 'removed' | null>(null)
const errorState = ref<'save' | 'remove' | null>(null)
const isLoading = ref(false) // prevent multiple rapid clicks
const isHovered = ref(false)
const isPending = ref(false)
const preToggleSaved = ref(false)

const handleToggleSave = async () => {
    if (isLoading.value) return
    isLoading.value = true
    preToggleSaved.value = isSaved(props.jobId)
    isPending.value = true
    try {
        const wasSaved = isSaved(props.jobId)
        await toggleSave(props.jobId)
        isPending.value = false

        // If we just saved the job, show 'saved' confirmation
        if (!wasSaved && isSaved(props.jobId)) {
            confirmationState.value = 'saved'
        }

        if (wasSaved && !isSaved(props.jobId)) {
            confirmationState.value = 'removed'
        }

        if (confirmationState.value !== null) {
            setTimeout(() => {
                confirmationState.value = null
            }, 1000)
        }

        await new Promise(resolve => setTimeout(resolve, 1000));
    } catch {
        isPending.value = false
        const wasSaved = preToggleSaved.value
        errorState.value = wasSaved ? 'remove' : 'save'
        setTimeout(() => {
            errorState.value = null
        }, 3000)
    } finally {
        isLoading.value = false
    }
}

const buttonSizeClass = computed(() => {
    switch (props.variant) {
        case 'carousel':
            return '!btn-sm'
        case 'featured':
        case 'detail':
            return '!btn-md'
        default:
            return '!btn-md'
    }
})


const useBookmarkStyle = (isSaved: boolean, showConfirmation: boolean): { style: string } => {
    if (!isSaved) {
        return {
            style: 'text-gray-600'
        }
    }

    if (showConfirmation) {
        return {
            style: 'text-green-700'
        }
    }

    return {
        style: 'text-red-700'
    }
}


const bookmarkStyle = computed(() => useBookmarkStyle(isSaved(props.jobId), confirmationState.value === 'saved'))

const displayedIconClass = computed(() => {
    if (isPending.value) {
        return preToggleSaved.value ? 'fas fa-trash text-lg text-red-400' : 'fas fa-bookmark text-lg text-[var(--ast-global-color-1)]'
    }
    const saved = isSaved(props.jobId)
    if (confirmationState.value === 'saved') return 'fas fa-bookmark'
    return saved ? 'fas fa-trash text-lg text-red-400' : 'fas fa-bookmark text-lg text-[var(--ast-global-color-1)]'
})
</script>
