// wordpress/wp-content/themes/wplokerbjm/src/lib/components/ui/Shared/JobDetail.svelte
<script module lang="ts">
  function extractImages(html: string): string[] {
    if (!html) return [];
    if (typeof DOMParser !== "undefined") {
      const parser = new DOMParser();
      const doc = parser.parseFromString(html, "text/html");
      const imgs = doc.querySelectorAll("img");
      return Array.from(imgs)
        .map((img) => img.src || img.getAttribute("data-src") || "")
        .filter(Boolean);
    }
    const srcs: string[] = [];
    const imgRe = /<img\s[^>]*?(?:src|data-src)=("|')([^"']+)\1/gi;
    let match: RegExpExecArray | null;
    while ((match = imgRe.exec(html))) {
      if (match[2]) srcs.push(match[2]);
    }
    return srcs.filter(Boolean);
  }
</script>

<script lang="ts">
  import { browser } from "$app/environment";
  import ViewerModule from "viewerjs";
  import "viewerjs/dist/viewer.min.css";
  import { SocialMediaPlatform } from "@/types";
  import { generalStore } from "$lib/stores/General.svelte";
  import { FormattingService } from "@/services/Formatting";
  import BookmarkButton from "@components/ui/Shared/BookmarkButton.svelte";
  import { SvelteDate } from "svelte/reactivity";
  import {
    ClockSolid,
    UserTieSolid,
    MapPinSolid,
    CircleInfoSolid,
    CircleCheckSolid,
    FileSignatureSolid,
    HandHoldingHeartSolid,
    AddressCardSolid,
    AddressBookSolid,
  } from "svelte-awesome-icons";
  import type { JobDetailResponse } from "@/types";
  import { timeEffect } from "$lib/utils/elements.svelte";
  import { page } from "$app/state";

  const { job }: { job: JobDetailResponse } = $props();

  let Viewer: any;

  const now = $state(new SvelteDate());

  const ringkasanPekerjaan = $derived(
    generalStore.useSummaryJob(job.ringkasanPekerjaan),
  );
  const contacts = $derived(generalStore.useContactsJob(job.contacts));
  const socialMediaItems = $derived(
    generalStore.useSocialMedia().socialMediaItems(job.social_media),
  );
  const timeAgo = $derived.by(() =>
    generalStore.useTimeAgo(job.post_time, now),
  );

  const allImages = $derived(
    [
      ...extractImages(job.tentang_perusahaan || ""),
      ...extractImages(job.deskripsi_pekerjaan || ""),
      ...extractImages(job.persyaratan || ""),
      ...extractImages(job.cara_melamar || ""),
      ...extractImages(job.benefit || ""),
    ].filter((v, i, a) => a.indexOf(v) === i),
  );
  let galleryRef = $state<HTMLElement>();
  let viewer = $state<Viewer>();

  class ViewerJSManager {
    static #eventHandlers: WeakMap<
      any,
      {
        onShown: () => void;
        onHide: () => void;
        onHidden: () => void;
      }
    > = new WeakMap();
    static viewerOptions(): Viewer.Options {
      const container = browser
        ? ((document.querySelector("#app") as HTMLElement) ?? document.body)
        : undefined;
      const opts: unknown = {
        hidden: true,
        container,
        focus: true,
        toolbar: {
          zoomIn: false,
          zoomOut: false,
          oneToOne: false,
          reset: false,
          prev: true,
          play: {
            show: false,
            size: "large",
          },
          next: true,
          rotateLeft: false,
          rotateRight: false,
          flipHorizontal: false,
          flipVertical: false,
        },
      };
      return opts as Viewer.Options;
    }

    static async setupViewer(): Promise<void> {
      if (!browser) return;
      if (!Viewer) {
        if (!browser) return;
        Viewer =
          (ViewerModule && (ViewerModule as any).default) ?? ViewerModule;
      }

      if (!galleryRef) return;

      viewer = new Viewer(galleryRef!, ViewerJSManager.viewerOptions());

      const viewerElement = (viewer as any).element;
      if (viewerElement) {
        const onShown = () => {
          viewerElement.removeAttribute("aria-hidden");
          viewerElement.removeAttribute("inert");
        };
        const onHide = () => {
          const focused = document.activeElement as HTMLElement | null;
          if (focused && viewerElement.contains(focused)) {
            focused.blur();
          }
        };
        const onHidden = () => {
          viewerElement.removeAttribute("aria-hidden");
          viewerElement.setAttribute("inert", "true");
        };
        viewerElement.addEventListener("shown", onShown);
        viewerElement.addEventListener("hide", onHide);
        viewerElement.addEventListener("hidden", onHidden);
        ViewerJSManager.#eventHandlers.set(viewer, {
          onShown,
          onHide,
          onHidden,
        });
      }
    }

    static destroyViewer(): void {
      if (viewer) {
        const viewerElement = (viewer as any).element;
        if (viewerElement && ViewerJSManager.#eventHandlers.has(viewer)) {
          const { onShown, onHide, onHidden } =
            ViewerJSManager.#eventHandlers.get(viewer)!;
          viewerElement.removeEventListener("shown", onShown);
          viewerElement.removeEventListener("hide", onHide);
          viewerElement.removeEventListener("hidden", onHidden);
        }
        try {
          viewer.destroy();
        } catch (e) {
          // ignore
        }
        viewer = undefined;
      }
    }
  }

  async function onWysiwygImgClick(e: MouseEvent): Promise<void> {
    const target = e.target as HTMLElement;
    if (target.tagName !== "IMG") return;

    const img = target as HTMLImageElement;
    const anchor = img.closest("a") as HTMLAnchorElement | null;

    anchor && e.preventDefault();

    const href = anchor?.href ?? "";
    const dataSrc = img.getAttribute("data-src") ?? "";

    const isImageUrl = (url: string | undefined | null): url is string =>
      typeof url === "string" &&
      /\.(avif|webp|jpe?g|png|gif|svg|bmp|tiff)(\?.*)?$/i.test(url);

    const src = isImageUrl(href)
      ? href
      : isImageUrl(img.src)
        ? img.src
        : isImageUrl(dataSrc)
          ? dataSrc
          : img.currentSrc || href || img.src || dataSrc || "";

    const imageIndex = allImages.indexOf(src);
    if (imageIndex >= 0) {
      await ViewerJSManager.setupViewer();
      if (!viewer) return;
      viewer!.show();
      viewer!.view(imageIndex);
    }
  }

  $effect(() => {
    const stopTime = timeEffect(now);
    return () => {
      stopTime();
      ViewerJSManager.destroyViewer();
    };
  });
</script>

<svelte:head>
  {#if page.data?.job && page.data.jobSchema}
    {@const jobId = Number(page.data.job.id)}
    {@html `<script type="application/ld+json" data-ld-type="JobPosting" data-ld-id="jobposting-${jobId}">${JSON.stringify(page.data.jobSchema)}</script>`}
  {/if}
</svelte:head>

<article class="space-y-8">
  <!-- Title + Summary -->
  {#if job.title || (ringkasanPekerjaan && ringkasanPekerjaan.length)}
    <section
      class="overflow-hidden border-1 border-[var(--wpl-global-color-1)] p-6 rounded-xl bg-[var(--wpl-global-color-5)]"
    >
      <div class="grid grid-cols-1 pt-6">
        <div class="flex items-start gap-4 flex-col">
          <div class="w-full flex flex-col">
            {#if job.title}
              <div class="justify-between flex flex-row items-start gap-2">
                <h1 class="text-2xl md:text-3xl xl:text-4xl font-bold mb-5">
                  {job.title}
                </h1>
                <div class="flex items-center shrink-0">
                  <BookmarkButton
                    jobId={Number(job.id) || 0}
                    variant="detail"
                  />
                </div>
              </div>
            {/if}

            <div class="flex flex-col wrap-anywhere mb-4">
              {#if job.nama_perusahaan}
                <div class="items-center gap-2 mb-2">
                  <UserTieSolid
                    class="text-[var(--wpl-global-color-1)] inline-block w-4 h-4"
                    aria-hidden="true"
                  />
                  <span class="font-bold ml-1">{job.nama_perusahaan}</span>
                </div>
              {/if}
              {#if job.post_time}
                <div class="items-center gap-2 mb-2">
                  <ClockSolid
                    class="text-[var(--wpl-global-color-1)] inline-block w-4 h-4"
                    aria-hidden="true"
                  />
                  <time class="font-bold ml-1" datetime={job.post_time}
                    >Diupdate: {timeAgo()}</time
                  >
                </div>
              {/if}
            </div>
          </div>
        </div>

        {#if ringkasanPekerjaan && ringkasanPekerjaan.length}
          <div
            class="mt-2 grid grid-cols-2 md:grid-cols-3 gap-4 text-sm md:text-base"
          >
            {#each ringkasanPekerjaan as row (row.label)}
              {@const Icon = row.icon}
              <div class="flex items-start gap-2">
                {#if Icon}
                  <Icon
                    class="text-[var(--wpl-global-color-1)] inline-block w-5 h-5"
                    aria-hidden="true"
                  />
                {/if}
                <div class="w-full">
                  <div class="font-bold">{row.label}</div>
                  <div
                    class="text-[var(--wpl-global-color-1)] font-bold wrap-anywhere"
                  >
                    {@html row.value}
                  </div>
                </div>
              </div>
            {/each}
          </div>
        {/if}
      </div>
    </section>
  {/if}

  <!-- Tentang Perusahaan -->
  {#if job.tentang_perusahaan}
    <section class="wysiwyg-content" aria-labelledby="about-company">
      <h2 id="about-company" class="text-2xl flex items-center gap-2 mb-4">
        <MapPinSolid
          class="text-[var(--wpl-global-color-1)] inline-block"
          aria-hidden="true"
        />
        <span class="font-semibold text-[var(--wpl-global-color-1)]"
          >Tentang Perusahaan</span
        >
      </h2>
      <div onclick={onWysiwygImgClick} role="presentation">
        {@html job.tentang_perusahaan}
      </div>
    </section>
  {/if}

  <!-- Deskripsi Pekerjaan -->
  {#if job.deskripsi_pekerjaan}
    <section class="wysiwyg-content" aria-labelledby="job-description">
      <h2 id="job-description" class="text-xl flex items-center gap-2 mb-4">
        <CircleInfoSolid
          class="text-[var(--wpl-global-color-1)] inline-block"
          aria-hidden="true"
        />
        <span class="font-semibold text-[var(--wpl-global-color-1)]"
          >Deskripsi Pekerjaan</span
        >
      </h2>
      <div onclick={onWysiwygImgClick} role="presentation">
        {@html job.deskripsi_pekerjaan}
      </div>
    </section>
  {/if}

  <!-- Persyaratan -->
  {#if job.persyaratan}
    <section class="wysiwyg-content" aria-labelledby="requirements">
      <h2 id="requirements" class="text-2xl flex items-center gap-2">
        <CircleCheckSolid
          class="text-[var(--wpl-global-color-1)] inline-block"
          aria-hidden="true"
        />
        <span class="font-semibold text-[var(--wpl-global-color-1)]"
          >Persyaratan</span
        >
      </h2>
      <div onclick={onWysiwygImgClick} role="presentation">
        {@html job.persyaratan}
      </div>
    </section>
  {/if}

  <!-- Cara Melamar -->
  {#if job.cara_melamar}
    <section class="wysiwyg-content" aria-labelledby="how-to-apply">
      <h2 id="how-to-apply" class="text-2xl flex items-center gap-2">
        <FileSignatureSolid
          class="text-[var(--wpl-global-color-1)] inline-block"
          aria-hidden="true"
        />
        <span class="font-semibold text-[var(--wpl-global-color-1)]"
          >Cara Melamar</span
        >
      </h2>
      <div onclick={onWysiwygImgClick} role="presentation">
        {@html job.cara_melamar}
      </div>
    </section>
  {/if}

  <!-- Benefit -->
  {#if job.benefit}
    <section class="wysiwyg-content" aria-labelledby="benefits">
      <h2 id="benefits" class="text-2xl flex items-center gap-2 mb-4">
        <HandHoldingHeartSolid
          class="text-[var(--wpl-global-color-1)] inline-block"
          aria-hidden="true"
        />
        <span class="font-semibold text-[var(--wpl-global-color-1)]"
          >Benefit</span
        >
      </h2>
      <div onclick={onWysiwygImgClick} role="presentation">
        {@html job.benefit}
      </div>
    </section>
  {/if}

  <!-- Kontak -->
  {#if contacts && contacts.length}
    <section class="aside-content" aria-labelledby="contacts-heading">
      <h2
        id="contacts-heading"
        class="text-2xl flex items-center justify-between mb-4"
      >
        <span class="flex items-center gap-2">
          <AddressCardSolid
            class="text-[var(--wpl-global-color-1)]"
            aria-hidden="true"
          />
          <span class="font-semibold text-[var(--wpl-global-color-1)]"
            >Kontak</span
          >
        </span>
      </h2>
      <address class="not-italic">
        <div class="grid grid-cols-1 gap-4 mt-4">
          <div
            class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-4"
          >
            <ul class="space-y-3">
              {#each contacts as contact (contact.label + contact.value)}
                {@const Icon = contact.icon}
                <li class="flex items-center">
                  {#if Icon}
                    <Icon
                      class="text-[var(--wpl-global-color-1)] w-6 text-center text-xl inline-block"
                      aria-hidden="true"
                    />
                  {/if}
                  <div class="ml-2 font-semibold text-md">
                    <span class="block font-semibold">{contact.label}:</span>
                    <a
                      href={contact.href}
                      target="_blank"
                      rel="noopener noreferrer nofollow"
                      class="block font-semibold wrap-anywhere max-w-full whitespace-normal text-[var(--wpl-global-color-1)] hover:underline"
                      >{contact.value}</a
                    >
                  </div>
                </li>
              {/each}
            </ul>
          </div>
        </div>
      </address>
    </section>
  {/if}

  <!-- Sosial Media -->
  {#if socialMediaItems && socialMediaItems.length}
    <section class="aside-content" aria-labelledby="social-media-heading">
      <h2
        id="social-media-heading"
        class="text-2xl flex items-center gap-2 mb-4"
      >
        <AddressBookSolid
          class="text-[var(--wpl-global-color-1)]"
          aria-hidden="true"
        />
        <span class="font-semibold text-[var(--wpl-global-color-1)]"
          >Sosial Media</span
        >
      </h2>
      <nav aria-label="Sosial media links">
        <ul
          class="grid grid-cols-1 gap-4 mt-4 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-4"
        >
          {#each socialMediaItems as item (item.platform + item.username)}
            {@const Icon = item.icon}
            <li class="flex items-center">
              {#if Icon}
                <Icon
                  class="text-[var(--wpl-global-color-1)] w-6 text-center text-xl inline-block"
                  aria-hidden="true"
                />
              {/if}
              <div class="ml-2 font-semibold text-md">
                <span class="block">{item.platform}:</span>
                <a
                  href={item.url}
                  target="_blank"
                  rel="noopener noreferrer nofollow"
                  class="block font-semibold break-words max-w-full whitespace-normal text-[var(--wpl-global-color-1)] hover:underline"
                >
                  {item.platform === SocialMediaPlatform.WhatsApp
                    ? item.username
                      ? FormattingService.formatPhone(item.username)
                      : ""
                    : (item.username ?? "")}
                </a>
              </div>
            </li>
          {/each}
        </ul>
      </nav>
    </section>
  {/if}
</article>
{#if allImages.length}
  <div bind:this={galleryRef} class="hidden">
    {#each allImages as img}
      <img src={img} alt="" />
    {/each}
  </div>
{/if}

<style lang="postcss">
  @reference "@css/app.css";
  @utility job-detail-base-content {
    @apply rounded-xl border-1 border-[var(--wpl-global-color-1)] bg-[var(--wpl-global-color-5)];
  }
  .wysiwyg-content {
    @apply job-detail-base-content px-3;
  }
  .aside-content {
    @apply job-detail-base-content p-4;
  }
</style>

// wordpress/wp-content/themes/astra-child/src/components/Shared/JobDetail.vue
<template>
  <div class="!space-y-8">
    <!-- Job Title -->
    <section v-if="job.title" class="top-0 backdrop-blur text-center">
      <div class="flex items-center justify-center gap-4">
        <h1 class="text-3xl !font-bold">{{ job.title }}</h1>
      </div>
      <div v-if="job.post_time" class="text-sm mt-2 flex items-center justify-center gap-2 font-semibold text-center">
        <i class="fas fa-clock text-blue-500 !inline-block !static"></i>
        <span>Diupdate: {{ computedTimeAgo }}</span>
        <BookmarkButton :job-id="job.id || 0" variant="detail" />
      </div>
    </section>

    <div v-if="job.title" class="divider"></div>

    <!-- Nama Perusahaan -->
    <section v-if="job.namaPerusahaan">
      <h2 class="text-2xl flex items-center gap-2 !mb-4">
        <i class="fas fa-user-tie text-blue-500 inline-block static"></i>
        <span class="!font-bold">{{ job.namaPerusahaan }}</span>
      </h2>
      <div class="divider"></div>
    </section>

    <!-- Tentang Perusahaan -->
    <section v-if="job.tentangPerusahaan">
      <h2 class="text-xl flex items-center gap-2 !mb-4">
        <i class="fas fa-map-marker-alt text-blue-600 inline-block static"></i>
        <span class="font-bold">Tentang Perusahaan</span>
      </h2>
      <Viewer v-html="job.tentangPerusahaan" @click="onWysiwygImgClick" />
      <div class="divider"></div>
    </section>

    <!-- Ringkasan Pekerjaan -->
    <section v-if="ringkasanPekerjaan && ringkasanPekerjaan.length">
      <h2 class="flex items-center gap-2 !mb-4">
        <i class="fas fa-clipboard-check text-blue-600"></i>
        <span class="font-bold">Ringkasan Pekerjaan</span>
      </h2>
      <div class="gap-4 mt-4">
        <div class="gap-x-6 gap-y-4 text-lg ml-2">
          <div v-for="row in ringkasanPekerjaan" :key="row.label" class="flex items-start lg:space-x-2 space-x-1 mb-2">
            <i :class="`fas ${row.icon} text-blue-600 !w-3 text-justify pt-2 inline-block static`"></i>
            <span class="!ml-3 !font-semibold text-wrap min-w-[40%] md:min-w-[20%]">{{ row.label }}</span>
            <span :class="[getLabelClass(row.label), '!font-semibold']">:</span>
            <span class="!font-semibold" v-html="row.value"></span>
          </div>
        </div>
      </div>
      <div class="divider"></div>
    </section>

    <!-- Deskripsi Pekerjaan -->
    <section v-if="job.deskripsiPekerjaan">
      <h2 class="text-xl flex items-center gap-2 !mb-4">
        <i class="fas fa-info-circle text-blue-600 inline-block static"></i>
        <span class="font-bold">Deskripsi Pekerjaan</span>
      </h2>
      <Viewer v-html="job.deskripsiPekerjaan" @click="onWysiwygImgClick" />
      <div class="divider"></div>
    </section>

    <!-- Persyaratan -->
    <section v-if="job.persyaratan">
      <h2 class="text-xl flex items-center gap-2 !mb-4">
        <i class="fas fa-check-circle text-blue-600 inline-block static"></i>
        <span class="font-bold">Persyaratan</span>
      </h2>
      <Viewer v-html="job.persyaratan" @click="onWysiwygImgClick" />
      <div class="divider"></div>
    </section>

    <!-- Cara Melamar -->
    <section v-if="job.caraMelamar">
      <h2 class="text-xl flex items-center gap-2 !mb-4">
        <i class="fas fa-file-signature text-blue-600 inline-block static"></i>
        <span class="font-bold">Cara Melamar</span>
      </h2>
      <Viewer v-html="job.caraMelamar" @click="onWysiwygImgClick" />
      <div class="divider"></div>
    </section>

    <!-- Benefit -->
    <section v-if="job.benefit">
      <h2 class="text-xl flex items-center gap-2 !mb-4">
        <i class="fas fa-hand-holding-heart text-blue-600 inline-block static"></i>
        <span class="font-bold">Benefit</span>
      </h2>
      <Viewer v-html="job.benefit" @click="onWysiwygImgClick" />
      <div class="divider"></div>
    </section>

    <!-- Kontak -->
    <section v-if="contacts && contacts.length">
      <h2 class="text-xl flex items-center justify-between !mb-4">
        <span class="flex items-center gap-2">
          <i class="fas fa-address-card text-blue-600"></i>
          <span class="font-bold">Kontak</span>
        </span>
      </h2>
      <div class="grid grid-cols-1 gap-4 mt-4">
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-4">
          <div v-for="contact in contacts" :key="contact.label" class="flex items-center">
            <i :class="`${contact.icon} text-blue-600 w-6 text-center text-xl inline-block static`"></i>
            <div class="ml-2 font-semibold text-md">
              <span class="block font-semibold">{{ contact.label }}:</span>
              <a :href="contact.href" target="_blank" rel="noopener noreferrer"
                class="block font-semibold break-all max-w-xs whitespace-normal">{{ contact.value }}</a>
            </div>
          </div>
        </div>
      </div>
      <div class="divider"></div>
    </section>

    <!-- Sosial Media -->
    <section v-if="socialMediaItems && socialMediaItems.length">
      <h2 class="text-xl flex items-center gap-2 !mb-4">
        <i class="fas fa-address-book text-blue-600"></i>
        <span class="font-bold">Sosial Media</span>
      </h2>
      <div class="grid grid-cols-1 gap-4 mt-4">
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-4">
          <div v-for="item in socialMediaItems" :key="item.platform + item.username" class="flex items-center">
            <i :class="`${item.icon} text-blue-600 w-6 text-center text-xl inline-block static`"></i>
            <div class="ml-2 font-semibold text-md">
              <span class="block">{{ item.platform }}:</span>
              <a :href="item.url" target="_blank" rel="noopener noreferrer"
                class="block font-semibold break-all max-w-xs whitespace-normal">
                {{ item.platform === 'Whatsapp' ? FormattingService.formatPhone(item.username) : item.username }}
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="divider"></div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import 'viewerjs/dist/viewer.css'
import { component as Viewer } from 'v-viewer'
import { useTimeAgo } from '@/composables/useTime'
import { FormattingService } from '@/services/Formatting'
import type { SingleOverlayResponse } from '@/types'
import { useSummaryJob, useContactsJob } from '@/composables/useSummary'
import { SocialMediaService } from '@/services/SosialMediaService'
import BookmarkButton from '@/components/Shared/BookmarkButton.vue'

const props = defineProps<{
  job: SingleOverlayResponse
}>()

const socialMediaItems = SocialMediaService.createSocialMediaItems(props.job.social_media)

const ringkasanPekerjaan = computed(() =>
  useSummaryJob(props.job.ringkasanPekerjaan)
)
const contacts = computed(() => useContactsJob(props.job.contacts))

const { timeAgo } = useTimeAgo(props.job.post_time)
const computedTimeAgo = computed(() => timeAgo.value)

function onWysiwygImgClick(e: MouseEvent) {
  const target = e.target as HTMLElement
  if (target.tagName === 'IMG' && target.parentElement?.tagName === 'A') {
    e.preventDefault()
  }
}

function getLabelClass(label: string) {
  switch (label) {
    case 'Jenis Pekerjaan':
      return 'lg:ml-3 ml-5'
    case 'Pendidikan':
    case 'Pengalaman':
    case 'Gender':
    case 'Usia':
    case 'Deadline':
    case 'Gaji':
    case 'Lokasi':
      return 'ml-5'
    default:
      return 'ml-4'
  }
}
</script>
