// wordpress/wp-content/themes/wplokerbjm/src/lib/components/layouts/Header.svelte
<script module lang="ts">
  import { debounce } from "@/utils";
  import { ThemeName } from "@/types";
  import { MediaQuery } from "svelte/reactivity";
  import { bookmarkStore } from "$lib/stores/Bookmark.svelte";
  import { isMobile } from "$lib/utils/elements.svelte";
  import { nonceManager } from "$lib/utils/Nonce.svelte";
  import { dynamicComponentStore } from "$lib/stores/DynamicComponent.svelte";
  import { browser } from "$app/environment";
  import { APIService } from "@/services/APIService";
  const isMobileValue = $derived.by(() => isMobile());
  let showBookmarkModal = $state(false);

  let logoSrcset = $state("");
  let logoSizes = $state("");
  let logoWidth = $state<number | undefined>(undefined);
  let logoHeight = $state<number | undefined>(undefined);
  let logoDecoding = $state<HTMLImgAttributes["decoding"]>(undefined);

  let showThemeModal = $state(false);
  let showLoginModal = $state(false);
  let loginUsername = $state("");
  let loginPassword = $state("");
  let loginError = $state("");
  let loginLoading = $state(false);

  class ThemeColorManager {
    private mediaQuery: MediaQuery | null = null;
    private debouncedSetTheme: (d: ThemeName) => void = () => {};
    public isDark = $state(false);
    public currentTheme = $state<ThemeName>(ThemeName.Light);
    private _initialized = false;

    private updateMetaThemeColor(dark: boolean): void {
      try {
        const root = document.documentElement;
        const cs = getComputedStyle(root);
        let color = (
          cs.getPropertyValue("--theme-color") ||
          cs.getPropertyValue("--wpl-global-color-4") ||
          ""
        ).trim();
        if (!color) color = dark ? "#0b1220" : "#ffffff";

        let meta = document.querySelector(
          'meta[name="theme-color"]',
        ) as HTMLMetaElement | null;
        if (!meta) {
          meta = document.createElement("meta");
          meta.name = "theme-color";
          document.head.appendChild(meta);
        }
        meta.setAttribute("content", color);
      } catch {
        console.error("Failed to update theme color meta tag");
      }
    }

    private setThemeDirect(theme: ThemeName): void {
      const newTheme = theme;
      const isDark = newTheme === ThemeName.Dark;

      if (this.currentTheme === newTheme) return;

      this.currentTheme = newTheme;

      window.requestAnimationFrame(() => {
        const applyTheme = () => {
          document.documentElement.classList.add("theme-switching");
          document.documentElement.setAttribute("data-theme", newTheme);
          if (isDark) {
            document.documentElement.classList.add(
              "wplokerbjm-dark-mode-enable",
            );
          } else {
            document.documentElement.classList.remove(
              "wplokerbjm-dark-mode-enable",
            );
          }
          this.updateMetaThemeColor(isDark);
        };

        // apply immediately, no view transition
        applyTheme();

        try {
          // Defer storage write off the critical paint path so it cannot
          // block rendering or cause forced reflow during theme toggles.
          const write = () => {
            try {
              localStorage.setItem("wplokerbjm-theme", newTheme);
            } catch (e) {
              console.warn(
                "Failed to write theme preference to localStorage",
                e,
              );
            }
          };
          if (typeof (window as any).requestIdleCallback === "function") {
            (window as any).requestIdleCallback(write);
          } else {
            setTimeout(write, 0);
          }
        } catch {
          console.error("Failed to schedule theme preference save");
        }
        setTimeout(() => {
          document.documentElement.classList.remove("theme-switching");
          // Give the browser a short moment to paint the theme change, then
          // trigger a single header measurement. This avoids forcing layout
          // during the theme toggle which causes long presentation delays.
          try {
            setTimeout(() => {
              requestAnimationFrame(() => {
                if (
                  typeof headerManager !== "undefined" &&
                  headerManager &&
                  headerManager.scheduleUpdate
                ) {
                  headerManager.scheduleUpdate();
                }
              });
            }, 50);
          } catch (e) {
            console.warn("Failed to schedule header measurement", e);
          }
        }, 30);
      });
    }

    public init(): void {
      if (this._initialized) return;
      this._initialized = true;
      this.debouncedSetTheme = debounce(
        (theme: ThemeName) => this.setThemeDirect(theme),
        10,
      );

      let saved = "";
      try {
        saved = localStorage.getItem("wplokerbjm-theme") || "";
      } catch {
        saved = "";
      }

      const systemPrefersDark = ((): boolean => {
        try {
          return (
            window.matchMedia &&
            window.matchMedia("(prefers-color-scheme: dark)").matches
          );
        } catch {
          return false;
        }
      })();

      if (
        saved === ThemeName.Dark ||
        saved === ThemeName.Lavender ||
        saved === ThemeName.Light
      ) {
        // persisted preference
        this.isDark = saved === ThemeName.Dark;
        this.setThemeDirect(saved as ThemeName);
      } else if (!saved && systemPrefersDark) {
        this.isDark = true;
        this.setThemeDirect(ThemeName.Dark);
      } else {
        this.isDark = false;
        this.setThemeDirect(ThemeName.Light);
      }

      try {
        this.mediaQuery = new MediaQuery("(prefers-color-scheme: dark)");
        $effect(() => {
          this.mediaQuery!.current;
          let hasStored = false;
          try {
            hasStored = !!localStorage.getItem("wplokerbjm-theme");
          } catch {
            hasStored = false;
          }
          if (!hasStored) {
            this.isDark = this.mediaQuery!.current;
            this.setThemeDirect(
              this.mediaQuery!.current ? ThemeName.Dark : ThemeName.Light,
            );
          }
        });
      } catch {
        this.mediaQuery = null;
      }

      $effect(() => {
        this.currentTheme;
        this.debouncedSetTheme(this.currentTheme);
      });
    }

    public setTheme(theme: ThemeName): void {
      // update boolean flag early so UI icon flips, but DON'T set currentTheme yet
      // otherwise setThemeDirect will erroneously early-return without updating DOM
      this.isDark = theme === ThemeName.Dark;

      // apply immediately for responsive UI, but keep debounced path for save/side-effects
      try {
        this.setThemeDirect(theme);
      } catch {
        // fallback to debounced if direct fails for some reason
        this.debouncedSetTheme(theme);
      }

      // ensure a debounced call remains to avoid double-write races
      try {
        if ((this.debouncedSetTheme as any)?.flush) {
          (this.debouncedSetTheme as any).flush();
        }
      } catch {
        // ignore
      }
    }
  }

  class HeaderManager {
    headerEl: HTMLElement | null = null;
    private _lastOffsetUpdate = $state(0);
    rafId: number | null = null;
    mutationObserver: MutationObserver | null = null;
    headerResizeObserver: ResizeObserver | null = null;

    scheduleUpdate = () => {
      if (this.rafId !== null) return;
      this.rafId = requestAnimationFrame(() => {
        this.rafId = null;
        this.updateOffsets();
      });
    };

    updateOffsets = () => {
      // Throttle expensive offset calculations to avoid layout thrash.
      const now = Date.now();
      if (this._lastOffsetUpdate && now - this._lastOffsetUpdate < 100) return;
      this._lastOffsetUpdate = now;

      this.headerEl = document.querySelector("header");
      try {
        this.updateHeaderHeight();
      } catch {
        headerStore.headerHeight = 0;
      }
    };

    private updateHeaderHeight = () => {
      if (this.headerEl) {
        const height = this.headerEl.offsetHeight;
        headerStore.headerHeight = height;
        headerStore.appEl?.style.setProperty(
          "--site-header-height",
          height + "px",
        );
        headerStore.appEl?.style.setProperty(
          "--site-scroll-padding-top",
          height + "px",
        );
      }
    };

    attachMutationObserver() {
      if (!browser) return;
      const htmlEl = document.documentElement;
      this.mutationObserver = new MutationObserver(() => {
        if (document.documentElement.classList.contains("theme-switching"))
          return;
        this.scheduleUpdate();
      });
      this.mutationObserver.observe(htmlEl, {
        attributes: true,
        attributeFilter: ["class", "style"],
      });
    }

    start = () => {
      if (!browser) return; // nothing to do on server
      // run immediately once
      this.scheduleUpdate();

      this.attachMutationObserver();

      // Attach ResizeObserver for header height changes
      if (this.headerEl && !this.headerResizeObserver) {
        this.headerResizeObserver = new ResizeObserver(() => {
          this.updateHeaderHeight();
        });
        this.headerResizeObserver.observe(this.headerEl);
      }
    };

    destroy = () => {
      // cleanup listeners and observers
      if (this.rafId !== null) cancelAnimationFrame(this.rafId);

      if (this.mutationObserver) {
        this.mutationObserver.disconnect();
        this.mutationObserver = null;
      }

      if (this.headerResizeObserver) {
        this.headerResizeObserver.disconnect();
        this.headerResizeObserver = null;
      }

      headerStore.appEl?.style.removeProperty("--site-header-height");
      headerStore.appEl?.style.removeProperty("--site-scroll-padding-top");
    };
  }

  class LoginManager {
    static async Login(): Promise<void> {
      try {
        const active = document.activeElement as HTMLElement | null;
        if (active && active.matches(".drawer-toggle")) {
          active.blur();
        }
      } catch {}

      loginLoading = true;
      loginError = "";
      try {
        const token = await APIService.getJWTGraphQL({
          username: loginUsername,
          password: loginPassword,
        });
        loginPassword = "";

        if (!token) {
          loginError = "Login gagal — periksa kredensial Anda.";
        } else {
          LoginManager.closeLogin();
        }
      } catch (e) {
        console.error("login error", e);
        loginError = "Terjadi kesalahan saat login.";
        loginPassword = ""; // also clear on error
      } finally {
        tick().then(() => {
          Promise.all([nonceManager.getNonceFromAPI, (loginLoading = false)]);
        });
      }
    }
    static async Logout(): Promise<void> {
      try {
        // perform logout directly against CMS GraphQL
      } catch {}
      window.location.reload();
    }
    static closeLogin() {
      showLoginModal = false;
      loginUsername = "";
      loginPassword = "";
      loginError = "";
      loginLoading = false;
    }
  }

  export const themeColorManager = new ThemeColorManager();
  export const headerManager = new HeaderManager();
</script>

<script lang="ts">
  import { onMount, onDestroy, tick } from "svelte";
  import type { HTMLImgAttributes } from "svelte/elements";
  import { GlobalNavigateTo } from "$lib/stores/Route.svelte";
  import { headerStore } from "$lib/stores/HeaderStore.svelte";
  import { innerWidth } from "svelte/reactivity/window";
  import {
    SunSolid,
    MoonSolid,
    BarsSolid,
    BookmarkSolid,
    ExternalLinkSolid,
    KeySolid,
  } from "svelte-awesome-icons";
  import { PortalManager } from "$lib/utils/elements.svelte";

  let {
    HeaderLogo = "",
    themeData,
  }: {
    HeaderLogo?: string;
    themeData?: import("@/types").WPLokerBJMThemedData | null;
  } = $props();
  let loginAdmin = $state(false);
  let _loginAdminPoll: number | null = null;
  const bookmarkJobs = $derived(bookmarkStore.jobs);
  function updateLogo(): void {
    try {
      const runtimeLogo = themeData?.logo?.logoUrl;
      const runtimeLogoSrcset = themeData?.logo?.logoSrcset;
      const runtimeLogoSizes = themeData?.logo?.logoSizes;
      const runtimeLogoDecoding = themeData?.logo?.logoDecoding;
      const runtimeLogoWidth = themeData?.logo?.logoWidth;
      const runtimeLogoHeight = themeData?.logo?.logoHeight;

      const parseDimension = (value: unknown): number | undefined => {
        if (typeof value === "number" && value > 0) return value;
        if (typeof value === "string" && value.trim()) {
          const parsed = Number(value.trim());
          if (!Number.isNaN(parsed) && parsed > 0) return parsed;
        }
        return undefined;
      };

      if (runtimeLogo) {
        HeaderLogo = runtimeLogo as string;
        logoSrcset = runtimeLogoSrcset || "";
        logoSizes = runtimeLogoSizes || "";
        logoDecoding = runtimeLogoDecoding;
        logoWidth = parseDimension(runtimeLogoWidth);
        logoHeight = parseDimension(runtimeLogoHeight);
      }
    } catch {
      console.error("Error updating logo");
    }
  }

  // Open bookmark modal
  function openBookmarkModal(): void {
    showBookmarkModal = true;
  }

  function showButtonLogin(): void {
    const w = window as any;
    const initial = !!w.loginadmin;
    loginAdmin = initial;
    const desc = Object.getOwnPropertyDescriptor(w, "loginadmin");
    if (!desc || desc.configurable) {
      let internal = initial;
      Object.defineProperty(w, "loginadmin", {
        configurable: true,
        enumerable: true,
        get() {
          return internal;
        },
        set(v: any) {
          internal = v;
          loginAdmin = !!v;
        },
      });
    } else {
      _loginAdminPoll = window.setInterval(() => {
        try {
          if ((w.loginadmin as boolean) !== loginAdmin)
            loginAdmin = !!w.loginadmin;
        } catch {}
      }, 300);
    }
  }

  updateLogo();
  onMount(() => {
    try {
      themeColorManager.init();
    } catch {
      console.error("Theme initialization error");
    }

    headerManager.start();
    showButtonLogin();
  });
  onDestroy(() => {
    headerManager?.destroy();
    if (_loginAdminPoll) {
      clearInterval(_loginAdminPoll);
      _loginAdminPoll = null;
    }
  });

  $effect(() => {
    if (showBookmarkModal && !dynamicComponentStore.BookmarkModal) {
      dynamicComponentStore.loadBookmarkModal();
    }
  });

  $effect(() => {
    if (showLoginModal && !dynamicComponentStore.LoginModal) {
      dynamicComponentStore.loadLoginModal();
    }
  });

  $effect(() => {
    // guard so this effect is a no-op during SSR
    if (typeof window === "undefined") return;
    innerWidth.current;
    headerManager.scheduleUpdate();
  });
</script>

<header
  class="fixed top-0 left-0 w-full bg-[var(--wpl-global-color-4)] border-b-3 border-[var(--wpl-global-color-5)] min-h-auto z-[60]"
>
  <div class="drawer drawer-end">
    <input
      id="header-drawer"
      type="checkbox"
      class="drawer-toggle"
      aria-hidden="true"
      tabindex="-1"
    />
    <div class="drawer-content">
      <div
        class="mr-auto ml-auto pl-4 pr-4 max-w-screen-xl w-full flex items-center justify-between"
      >
        <div class="mt-3">
          <a
            href="/"
            class="focus:outline-none"
            onclick={(e) => {
              e.preventDefault();
              GlobalNavigateTo("/");
            }}
          >
            {#if HeaderLogo}
              <img
                src={HeaderLogo}
                srcset={logoSrcset}
                sizes={logoSizes}
                decoding={logoDecoding}
                alt="Site logo"
                width={logoWidth}
                height={logoHeight}
                fetchpriority="high"
                class="h-12 w-auto mb-2 md:h-16 md:w-auto"
              />
            {/if}
          </a>
        </div>
        <div class="flex items-center gap-1 mt-5">
          <!-- Color/theme switcher -->
          <div class="p-1">
            <button
              class="flex items-center gap-2 p-2 rounded focus:outline-none"
              aria-label="Choose color theme"
              title="Pilih tema warna"
              onclick={() => (showThemeModal = true)}
            >
              {#if themeColorManager.isDark}
                <MoonSolid class="w-5 h-5" style="color: var(--icon-color);" />
              {:else if themeColorManager.currentTheme === ThemeName.Lavender}
                <SunSolid class="w-5 h-5" style="color: var(--icon-color);" />
              {:else}
                <SunSolid class="w-5 h-5" style="color: var(--icon-color);" />
              {/if}
            </button>
          </div>

          {#if showThemeModal}
            <div use:PortalManager.teleport={"#app"}>
              <div class="modal modal-open z-[1100]">
                <div class="modal-box">
                  <h3 class="font-semibold text-lg">Pilih Tema</h3>
                  <p class="py-2 text-sm text-muted">
                    Pilih tema yang ingin Anda gunakan.
                  </p>
                  <div class="flex gap-3 mt-3">
                    <button
                      class="btn flex-1"
                      class:btn-primary={themeColorManager.currentTheme ===
                        ThemeName.Light}
                      onclick={() => {
                        themeColorManager.setTheme(ThemeName.Light);
                        showThemeModal = false;
                      }}
                    >
                      Light
                    </button>
                    <button
                      class="btn flex-1"
                      class:btn-primary={themeColorManager.currentTheme ===
                        ThemeName.Dark}
                      onclick={() => {
                        themeColorManager.setTheme(ThemeName.Dark);
                        showThemeModal = false;
                      }}
                    >
                      Dark
                    </button>
                    <button
                      class="btn flex-1"
                      class:btn-primary={themeColorManager.currentTheme ===
                        ThemeName.Lavender}
                      onclick={() => {
                        themeColorManager.setTheme(ThemeName.Lavender);
                        showThemeModal = false;
                      }}
                    >
                      Lavender
                    </button>
                  </div>
                  <div class="modal-action">
                    <button class="btn" onclick={() => (showThemeModal = false)}
                      >Close</button
                    >
                  </div>
                </div>
              </div>
            </div>
          {/if}

          <button
            onclick={openBookmarkModal}
            class="btn btn-circle md:flex relative border-[var(--wpl-global-color-1)] border-1 hover:border-2"
            aria-label="Lowongan tersimpan"
            title="Lowongan tersimpan"
          >
            <BookmarkSolid
              class="h-5 w-5 text-[var(--wpl-global-color-1)]"
              aria-hidden="true"
              focusable="false"
            />
            {#if bookmarkJobs.length > 0}
              <span
                class="absolute -top-2 -right-1 bg-[var(--wpl-global-color-1)] text-white text-xs rounded-full px-2 py-0.1 z-10"
              >
                {bookmarkJobs.length}
              </span>
            {/if}
          </button>

          <!-- Login button (desktop) -->
          {#if loginAdmin}
            <button
              class="btn rounded-full font-semibold bg-[var(--wpl-global-color-5)] text-[var(--wpl-global-color-1)] relative border-1 border-[var(--wpl-global-color-1)] hover:border-2 ml-2 hidden md:flex"
              onclick={() => (showLoginModal = true)}
              aria-label="Masuk"
              title="Masuk"
            >
              <KeySolid class="h-5 w-5" aria-hidden="true" focusable="false" />
              Masuk
            </button>
          {/if}
          <a
            class="btn font-semibold border-1 border-[var(--wpl-global-color-1)] bg-[var(--wpl-global-color-5)] text-[var(--wpl-global-color-1)] hover:bg-[var(--wpl-global-color-1)] hover:text-[var(--wpl-global-color-5)] hidden rounded-full md:inline-flex"
            href="/pasang-iklan-loker"
            onclick={(e) => {
              e.preventDefault();
              GlobalNavigateTo("/pasang-iklan-loker");
            }}
          >
            <ExternalLinkSolid
              class="h-6 w-6"
              aria-hidden="true"
              focusable="false"
            />
            Pasang Iklan Loker
          </a>
          <!-- Drawer toggle button, shown only on mobile -->
          {#if isMobileValue}
            <label
              for="header-drawer"
              class="btn btn-ghost btn-sm md:btn-md"
              aria-label="Open navigation menu"
            >
              <BarsSolid class="h-5 w-5" aria-hidden="true" focusable="false" />
            </label>
          {/if}
        </div>
      </div>
    </div>
    <!-- Mobile drawer side. margin-top reads the same CSS var we set in JS (--site-header-top) -->
    {#if isMobileValue}
      <div id="header-drawer-side" class="drawer-side z-50">
        <label
          for="header-drawer"
          aria-label="Close navigation menu"
          class="drawer-overlay"
        ></label>
        <ul
          class="menu bg-base-200 text-base-content min-h-full w-auto max-w-[90vw] p-4 px-2 gap-4"
        >
          {#if loginAdmin}
            <li>
              <button
                class="btn font-semibold border-1 border-[var(--wpl-global-color-1)] bg-[var(--wpl-global-color-4)] text-[var(--wpl-global-color-1)] justify-center"
                onclick={() => {
                  showLoginModal = true;
                  document.getElementById("header-drawer")?.click();
                }}
              >
                <KeySolid
                  class="h-5 w-5"
                  aria-hidden="true"
                  focusable="false"
                />
                Masuk
              </button>
            </li>
          {/if}
          <li>
            <a
              href="/pasang-iklan-loker"
              class="btn font-semibold border-1 border-[var(--wpl-global-color-1)] bg-[var(--wpl-global-color-4)] text-[var(--wpl-global-color-1)] justify-center"
              onclick={(e) => {
                e.preventDefault();
                GlobalNavigateTo("/pasang-iklan-loker");
                document.getElementById("header-drawer")?.click();
              }}
            >
              <ExternalLinkSolid
                class="h-6 w-6"
                aria-hidden="true"
                focusable="false"
              />
              Pasang Iklan Loker
            </a>
          </li>
        </ul>
      </div>
    {/if}
  </div>
  {#if showBookmarkModal && dynamicComponentStore.BookmarkModal}
    {#await dynamicComponentStore.BookmarkModal then BookmarkModal}
      <BookmarkModal bind:open={showBookmarkModal} />
    {/await}
  {/if}

  {#if showLoginModal && dynamicComponentStore.LoginModal}
    {#await dynamicComponentStore.LoginModal then LoginModal}
      <LoginModal
        bind:open={showLoginModal}
        bind:username={loginUsername}
        bind:password={loginPassword}
        error={loginError}
        loading={loginLoading}
        onClose={LoginManager.closeLogin}
        onLogin={LoginManager.Login}
      />
    {/await}
  {/if}
</header>

// wordpress/wp-content/themes/astra-child/src/layouts/Header.vue
<template>
  <header
    class="fixed sm:relative left-0 w-full bg-[var(--ast-global-color-4)] !pb-4 border-b-2 border-[var(--ast-global-color-7)] min-h-auto z-[60]"
    style="top:var(--site-header-top, 0)">
    <div class="drawer drawer-end">
      <input id="header-drawer" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <div class="!mr-auto !ml-auto !pl-4 !pr-4 max-w-[1240px] flex items-center justify-between">
          <div class="mt-4" v-html="props.logo"></div>
          <div class="flex items-center !gap-2 !mt-5">
            <!-- Color/theme switcher -->
            <div class="!backdrop-blur-lg rounded-full shadow-lg !p-2">
              <label class="flex cursor-pointer gap-2 items-center" :aria-hidden="false">
                <span class="relative w-12 h-6 flex items-center" role="switch" :aria-checked="isDark">
                  <span class="absolute inset-0 rounded-full bg-gray-200 dark:bg-slate-700 transition-colors"></span>
                  <span
                    class="absolute top-0 left-0 w-6 h-6 rounded-full bg-white dark:bg-slate-800 shadow transition-transform"
                    :style="{ transform: isDark ? 'translateX(100%)' : 'translateX(0)' }"></span>
                  <!-- Sun icon -->
                  <svg class="absolute left-1 top-1 w-4 h-4 transition-all z-10"
                    :class="isDark ? 'opacity-40 grayscale' : 'opacity-100'" style="color: var(--icon-color);"
                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true">
                    <g stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none"
                      stroke="currentColor">
                      <circle cx="12" cy="12" r="4"></circle>
                      <path d="M12 2v2"></path>
                      <path d="M12 20v2"></path>
                      <path d="m4.93 4.93 1.41 1.41"></path>
                      <path d="m17.66 17.66 1.41 1.41"></path>
                      <path d="M2 12h2"></path>
                      <path d="M20 12h2"></path>
                      <path d="m6.34 17.66-1.41 1.41"></path>
                      <path d="m19.07 4.93-1.41 1.41"></path>
                    </g>
                  </svg>
                  <!-- Moon icon -->
                  <svg class="absolute right-1 top-1 w-4 h-4 transition-all z-10"
                    :class="!isDark ? 'opacity-40 grayscale' : 'opacity-100'" style="color: var(--icon-color);"
                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true">
                    <g stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none"
                      stroke="currentColor">
                      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"></path>
                    </g>
                  </svg>
                  <input type="checkbox" value="dark"
                    class="toggle theme-controller focus:ring-2 focus:ring-blue-400 absolute w-12 h-6 opacity-0 cursor-pointer"
                    aria-label="Toggle color theme" :aria-checked="isDark" v-model="isDark" />
                </span>
              </label>
            </div>

            <!-- Bookmark button on desktop -->
            <button @click="showBookmarkModal = true" class="btn !btn-circle md:flex relative"
              aria-label="Lowongan tersimpan" title="Lowongan tersimpan">
              <i class="fas fa-bookmark"></i>
              <span v-if="bookmarkStore.jobs.length > 0"
                class="absolute -top-2 -right-1 bg-[var(--ast-global-color-1)] text-white text-xs rounded-full px-2 py-0.1 z-10">{{
                  bookmarkStore.jobs.length }}</span>
            </button>
            <button class="btn btn-primary hidden md:block" @click="openWindow('/pasang-iklan-loker')">
              <i class="fas fa-arrow-up-right-from-square"></i>
              Pasang Iklan Loker
            </button>
            <!-- Drawer toggle button, shown only on mobile -->
            <label v-if="isMobile" for="header-drawer" class="drawer-button">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </label>
          </div>
        </div>
      </div>
      <!-- Mobile drawer side. margin-top reads the same CSS var we set in JS (--site-header-top) -->
      <div v-if="isMobile" class="drawer-side z-50" style="margin-top:var(--site-header-top, 0)">
        <label for="header-drawer" aria-label="close sidebar" class="drawer-overlay"></label>
        <ul class="menu bg-base-200 text-base-content min-h-full w-auto max-w-[90vw] !p-4 !mx-4 !px-2 !gap-4">
          <li>
            <a href="/pasang-iklan-loker" class="!btn !btn-primary justify-start">
              <i class="fas fa-arrow-up-right-from-square"></i>
              Pasang Iklan Loker
            </a>
          </li>
        </ul>
      </div>
    </div>
    <BookmarkedModal v-if="showBookmarkModal" v-model="showBookmarkModal" />
  </header>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, defineAsyncComponent } from 'vue';
import { useTheme } from '@/composables/useTheme';
import { type LayoutProps } from '@/types/Component';
import { getWpAdminBarTopOffset } from '@/utils/elements';
import { useSavedJobsStore } from '@/stores';
const BookmarkedModal = defineAsyncComponent(() => import('@/components/Header/BookmarkedModal.vue'));

const props = defineProps<LayoutProps>();

const bookmarkStore = useSavedJobsStore();
const showBookmarkModal = ref(false);

// reactive: measured WP admin bar offset (px)
const adminBarHeight = ref(0);

// Mirror Tailwind's md breakpoint so JS and CSS are consistent.
// `isMobile` toggles which layout logic we run (fixed header/padding on mobile).
const isMobile = ref(window.innerWidth < 768);
// matchMedia is more precise for breakpoint detection than checking innerWidth manually
const mobileMq = window.matchMedia('(max-width: 767.98px)');

const { isDark } = useTheme();

// store previous main paddingTop so we can restore it when component unmounts or when leaving mobile layout
let previousMainPadding: string | null = null;

let headerEl: HTMLElement | null = null;
let mainEl: HTMLElement | null = null;
let adminBarEl: HTMLElement | null = null;
let rafId: number | null = null;
let mutationObserver: MutationObserver | null = null;
let mqListener: ((ev: MediaQueryListEvent) => void) | null = null;

function scheduleUpdate() {
  if (rafId !== null) return;
  rafId = requestAnimationFrame(() => {
    rafId = null;
    // refresh mobile flag from matchMedia and then recompute offsets
    isMobile.value = mobileMq.matches;
    updateOffsets();
  });
}

function updateOffsets() {
  if (!headerEl) headerEl = document.querySelector('header') as HTMLElement | null;
  if (!mainEl) mainEl = document.querySelector('main') as HTMLElement | null;
  if (!adminBarEl) adminBarEl = document.getElementById('wpadminbar') as HTMLElement | null;

  // measure admin bar and compute top offset (only relevant for mobile)
  adminBarHeight.value = getWpAdminBarTopOffset();

  const top = isMobile.value ? adminBarHeight.value : 0;
  try {
    document.documentElement.style.setProperty('--site-header-top', top + 'px');
  } catch {
    // ignore: operations may fail in some restricted contexts (SSR or CSP)
  }

  if (isMobile.value && headerEl && mainEl) {
    const headerHeight = headerEl.offsetHeight || 0;
    if (previousMainPadding === null) previousMainPadding = mainEl.style.paddingTop || '';
    // still set inline padding for main for immediate layout safety while CSS var support propagates
    // (we also set --site-header-height for future CSS-only handling)
    mainEl.style.paddingTop = headerHeight + 'px';
    try {
      document.documentElement.style.setProperty('--site-header-height', headerHeight + 'px');
    } catch {
      /* ignore */
    }
  } else {
    // reset CSS vars and restore previous main padding when leaving mobile
    try {
      document.documentElement.style.setProperty('--site-header-top', '0px');
      document.documentElement.style.setProperty('--site-header-height', '0px');
    } catch {
      /* ignore */
    }
    if (mainEl && previousMainPadding !== null) {
      mainEl.style.paddingTop = previousMainPadding;
    }
  }
}

onMounted(() => {
  // cache DOM nodes once on mount for faster repeated access
  headerEl = document.querySelector('header') as HTMLElement | null;
  mainEl = document.querySelector('main') as HTMLElement | null;
  adminBarEl = document.getElementById('wpadminbar') as HTMLElement | null;

  // Use rAF-debounced listeners for scroll/resize to avoid layout thrashing.
  // We use passive listeners for scroll/resize to avoid blocking the main thread.
  window.addEventListener('resize', scheduleUpdate, { passive: true });
  window.addEventListener('scroll', scheduleUpdate, { passive: true });
  // run once immediately to initialize CSS vars and padding
  scheduleUpdate();

  // keep isMobile in sync with the matchMedia; scheduleUpdate will pick up the change
  mqListener = () => scheduleUpdate();
  mobileMq.addEventListener('change', mqListener);

  // Observe html attribute changes only (class/style) to detect WP toggles without watching whole body
  const htmlEl = document.documentElement;
  // observe changes to <html> attributes that may affect header positioning (WP toggles classes/style)
  mutationObserver = new MutationObserver(() => scheduleUpdate());
  mutationObserver.observe(htmlEl, { attributes: true, attributeFilter: ['class', 'style'] });
});

onUnmounted(() => {
  window.removeEventListener('resize', scheduleUpdate);
  window.removeEventListener('scroll', scheduleUpdate);
  if (rafId !== null) cancelAnimationFrame(rafId);
  if (mainEl && previousMainPadding !== null) {
    mainEl.style.paddingTop = previousMainPadding;
  }
  if (mutationObserver) {
    // stop observing to avoid memory leaks
    mutationObserver.disconnect();
    mutationObserver = null;
  }

  // remove matchMedia listener and clear CSS vars
  // remove media listener and CSS vars on unmount so other parts of the app are not affected
  if (mqListener) mobileMq.removeEventListener('change', mqListener);
  mqListener = null;

  document.documentElement.style.removeProperty('--site-header-top');
  document.documentElement.style.removeProperty('--site-header-height');
});

function openWindow(url: string) {
  window.open(url, '_blank');
}
</script>
